In [16]:
import os
import pandas as pd
from pandas import read_csv
from pandas import DataFrame
from math import *
import math
from sympy import *
from sympy.abc import x,y,z,a,b,c,d
import numpy as np
import numpy
import csv
from math import e

def preprocessing(before_filename, after_filename):
    train_dataset = read_csv(before_filename, header=0, index_col=None)
    train_values = train_dataset.values

    power = train_values[:, 0]
    temperature = train_values[:, 1]
    humidity = train_values[:, 2]
    speed = train_values[:, 3]
    common = [1 for i in range(power.shape[0])]

    transfer_power = []
    transfer_temperature = []
    transfer_humidity = []
    transfer_speed = []

    except_value = -5.0

    for index in range(len(power)):
        if round(log(power[index], e), 2) == -inf:
            transfer_power.append(except_value)
        else:
            transfer_power.append(round(log(power[index], e), 2))

    for index in range(len(temperature)):
        if round(log(temperature[index], e), 2) == -inf:
            transfer_temperature.append(except_value)
        else:
            transfer_temperature.append(round(log(temperature[index], e), 2))

    for index in range(len(humidity)):
        if round(log(humidity[index], e), 2) == -inf:
            transfer_humidity.append(except_value)
        else:
            transfer_humidity.append(round(log(humidity[index], e), 2))

    for index in range(len(speed)):
        if round(log(speed[index], e), 2) == -inf:
            transfer_speed.append(except_value)
        else:
            transfer_speed.append(round(log(speed[index], e), 2))

    transfer_common = numpy.array(common)

    Data = {'power': transfer_power, 'temperature': transfer_temperature, 'humidity': transfer_humidity,
            'speed': transfer_speed, 'common': transfer_common}
    df = DataFrame(Data, columns=['power', 'temperature', 'humidity', 'speed', 'common'])
    df.to_csv(after_filename, index=False)

def train_start(train_filename):
    dt = read_csv(train_filename, header=0, index_col=False)
    df = pd.DataFrame(dt)
    i = 0
    while i < (len(df.values)/2):
    
        try:
            temp1 = df.sample(4, frac=None, replace=True, weights=None, random_state=None, axis=None)
            a = np.array(temp1.values[:, 1:])
            b = np.array(temp1.values[0:, 0])
            x = np.linalg.solve(a, b)
            dataframe = pd.DataFrame({'X1': x[0], 'X2': x[1], 'X3': x[2], 'X4': x[3]}, index=[i])
            dataframe.to_csv("Xee_A.csv", mode='a', header=None, index=True, sep=',')#Xee_A.csv...Xee_F.csv
            i = i + 1
            print('第%d组系数' % (i))
            print(x)
            total_mape = 0
            m = 2.7182818
            for line in range(len(df.values)):
                predict_log_values = np.dot(df.values[line][1:], x.reshape(4, 1))

                predict_value = pow(e, predict_log_values)

                mape = abs(pow(e, df.values[line][0]) - predict_value) / pow(e, df.values[line][0])
                total_mape = total_mape + mape

            average_mape = total_mape / len(df.values)
            print(average_mape)
            dataframe = pd.DataFrame({'X5': average_mape}, index=[i - 1])
            dataframe.to_csv("Xe1_A.csv", mode='a', header=None, index=True, sep=',')#Xe1_A.csv...Xe1_F.csv
        except:
            i = i - 1



def test_start(test_filename, n):
    dt = read_csv(test_filename, header=0, index_col=False)
    df = pd.DataFrame(dt)
    para = para_median(n)
    mape = 0
#    print(para)
    for index in range(len(df.values)):
        X = df.values[index][1:]
        testY = df.values[index][0]
        para = np.array(para).reshape(4, 1)
        predict = np.dot(X, para)
        mape = mape + abs(pow(e,testY)-pow(e,predict))/pow(e,testY)
    print(mape/len(df.values))

def para_median(n):
    lc = pd.DataFrame(pd.read_csv('Xe1_A.csv', header=None, names=['xulie', 'wucha']))#Xe1_A.csv...Xe1_F.csv
    tdd = lc.sort_values(by='wucha', ascending=True).head(n)
    index = list(tdd['xulie'])
    dt = pd.read_csv('Xee_A.csv', header=None, names=['xulie', '参数1', '参数2', '参数3', '参数4'])#Xee_A.csv...Xee_F.csv
    df = pd.DataFrame(dt)
    X = []
    for i in index:
        X.append([df.values[i][1],df.values[i][2],df.values[i][3],df.values[i][4]])
    X = np.array(X)
    para1 = np.median(X[:, 0])
    para2 = np.median(X[:, 1])
    para3 = np.median(X[:, 2])
    para4 = np.median(X[:, 3])
    return [para1, para2, para3, para4]


if __name__ == "__main__":
    preprocessing("trainingA.csv", "trainA.csv")#trainingA.csv/trainA.csv...trainingF.csv/trainF.csv
    preprocessing("validationA.csv", "valA.csv")#validationA.csv/valA.csv...validationF.csv/valF.csv
    train_start("trainA.csv")#trainA.csv...trainF.csv
    test_start("valA.csv",50)#valA.csv...valF.csv
    

第1组系数
[0.42587883 0.51497407 0.17546973 7.3249581 ]
0.39134892296706036
第2组系数
[ 0.57725822 -0.05757783  0.38185462  7.25766643]
0.30584968442681004
第3组系数
[0.13541851 0.71581159 0.08670534 6.83173107]
0.3305738246265509
第4组系数
[ 0.38083538 -2.88697789  2.9968059   8.30785995]
239.01071093129184
第5组系数
[ 1.20612349 -0.30203874  0.1748168   6.96477726]
0.36585125216057107
第6组系数
[-0.25        0.92013889 -1.95659722  4.04821181]
53.02557853425666
第7组系数
[-0.14267468 -0.85498377 -0.39260284  5.16548837]
0.563643656773942
第8组系数
[ 0.6982119  -0.8848334   0.27270842  6.83924259]
0.5744441067874914
第9组系数
[ 0.01249366  1.57638959 -0.230408    6.17101065]
0.4922549557370618
第10组系数
[ 0.20185575 -0.56681021 -1.74248095  4.31696446]
21.579275112699474
第11组系数
[-43.40540541  -9.41441441 126.06126126 113.12762162]
1.937494981948354e+85
第12组系数
[ 0.72907392 -1.48843188  1.42698602  7.77526303]
1.8988715061251507
第13组系数
[ 3.17299953 -0.82411391 -0.54663568  7.07467277]
0.8865237605035873
第14组系数
[ 3.5        -

5.222556996667387
第109组系数
[ 0.90841375 -0.43179896 -0.01926945  6.86912377]
0.3981853077625176
第110组系数
[-0.69101004 -0.04057228 -0.06525731  5.48093487]
0.5113842272280582
第111组系数
[ 1.53663004 -0.21794872  0.22502383  7.26155627]
0.3945257119472055
第112组系数
[-1.15528491  0.1722488  -0.44588811  4.74288653]
1.3654004726798041
第113组系数
[0.70093309 0.14900379 0.61413389 7.63112977]
0.3439659996985642
第114组系数
[0.23014865 0.19163235 1.00768999 7.79830994]
0.42191079866613035
第115组系数
[ 1.79204178e-05 -3.16362213e-01  6.48530235e-02  6.09368372e+00]
0.25321083599514804
第116组系数
[ 2.69722905e-01  2.88111177e-03 -5.55054656e-01  5.70639234e+00]
0.4815829573127443
第117组系数
[ 2.32518272 -0.73687708 -1.95338206  5.58342405]
30.334252141808623
第118组系数
[ 6.1875     1.125      2.2900641 11.83625  ]
0.9795649881779025
第119组系数
[-0.0762446  -0.16684098  0.28458374  6.69671001]
0.40150279098549224
第120组系数
[ 0.89852862 -0.58789401 -0.82047371  5.77271398]
0.971706979315137
第121组系数
[ 1.75918196 -0.89746425 -0.

512535.413689144
第215组系数
[ 0.94108713 -0.61659652 -0.51428093  5.98173894]
0.5024670496516591
第216组系数
[ 0.41815233  0.18300893 -1.41889046  5.39685651]
8.455748739088131
第217组系数
[ 0.64550588 -0.03754006  0.88425149  7.90242408]
0.4277029732070865
第218组系数
[-0.35817079 -0.89308742 -0.13695806  4.89344305]
0.49918295032924237
第219组系数
[0.60914761 0.0338755  0.64501406 7.2689289 ]
0.36707493151143167
第220组系数
[ 0.30846834 -2.2918696  -0.35200278  5.30140195]
11.388591632783976
第221组系数
[ 0.83323419 -0.39440809  0.11335845  7.17858153]
0.5163259474436706
第222组系数
[ 0.70434565 -0.97516971  0.8216114   7.23483391]
0.6745379954753579
第223组系数
[-0.02582573 -0.1913278   0.26096902  6.5055204 ]
0.28255790325411195
第224组系数
[ 0.46122793 -0.04465213  0.22354621  6.62610332]
0.30675708940771856
第225组系数
[0.09107782 0.01317906 0.1469058  6.77773402]
0.35403650131423187
第226组系数
[ 0.22844175 -0.25567322 -0.17821483  6.02701059]
0.26487171857178887
第227组系数
[-0.36175205 -0.90190793  0.07599587  5.39186044]
0.50

0.627287290489557
第322组系数
[ 0.32427088 -1.0502554   0.20504202  6.41446169]
0.6726578214570781
第323组系数
[ 0.8477746  -0.16807929  0.30986473  6.89608728]
0.3592211892919134
第324组系数
[0.83911355 0.44878697 0.75147818 8.30880824]
0.5359386789333659
第325组系数
[0.30912445 0.36249989 0.15918903 7.16150132]
0.37315724719233845
第326组系数
[1.22855216 0.46578752 0.23174904 7.76331452]
0.42823291526729157
第327组系数
[0.58437204 1.07686498 0.04574173 7.65216756]
0.6561163437411319
第328组系数
[ 1.26776389 -3.2222243  -1.02731211  4.38640616]
266.81718238728996
第329组系数
[ 1.72627373 -1.79220779  0.42        6.95352388]
2.6952235653495675
第330组系数
[ 0.49832748 -0.39305361  0.40473504  6.94900157]
0.32784452952152454
第331组系数
[ 0.19732882  0.07174837 -0.30754668  5.84720534]
0.33695786794197735
第332组系数
[ 0.37076556 -0.07373002  0.34350657  7.15209139]
0.32619481245239274
第333组系数
[ 0.24614671 -0.65291663  0.27534081  6.48236168]
0.37199697598789777
第334组系数
[ 4.65764706  0.16470588 -2.42996078  5.09804   ]
36.3427449

109614.25300645696
第429组系数
[0.23930724 0.65035139 0.21195535 7.48151536]
0.6014993227184923
第430组系数
[-1.18661828  6.22302867  4.43192579 15.05013507]
44.44596942346937
第431组系数
[ 1.22360449  0.44289029 -0.08817842  7.37204847]
0.44840174325769505
第432组系数
[ 1.2755243  -0.24940349  0.2449663   7.14380133]
0.3699109748608989
第433组系数
[-3.85395345 -8.77409202 11.66246264 15.39498551]
8706240503144560.0
第434组系数
[ 2.83987235  3.65045992  0.84862024 11.18490558]
1.9921079759944293
第435组系数
[0.60414053 0.4642409  1.8161857  8.84606023]
0.5906444300828494
第436组系数
[0.51445365 0.15359945 0.09119339 7.10049543]
0.33484777231732343
第437组系数
[ 0.02356071 -0.7201216   0.03097093  5.93958769]
0.37229605914294395
第438组系数
[ 0.41812164  0.38636364 -0.08200786  6.8914819 ]
0.3694495716175456
第439组系数
[ 1.94230306 -1.95452817  0.27192029  7.67386795]
9.704613625667449
第440组系数
[-4.20288729 -5.52355636 -0.61712743  1.17460085]
5956142.289910658
第441组系数
[-7.02083803 -5.07204249 -2.35024411 -5.4056929 ]
23416873422

0.6773035497934522
第534组系数
[0.19746534 0.11774263 0.44757366 7.15515273]
0.30454205116719213
第535组系数
[ 0.15357755 -0.08213538  0.03506217  6.33160021]
0.22147277236733084
第536组系数
[ -3.92664931 -12.25086806  -2.53776042  -4.57562066]
3.5627009232788726e+18
第537组系数
[ 2.49863612e-01 -3.75834896e-16 -1.92034915e-01  6.40510638e+00]
0.3454309791191615
第538组系数
[-0.28188776 -3.93121144 -0.13882297  4.21572496]
5661.656690280039
第539组系数
[ 1.17768776 -4.48872983  0.04653243  5.95530798]
245965.87101734892
第540组系数
[ 0.57828736  0.5676104  -0.09261856  6.95768009]
0.3579667304573184
第541组系数
[-3.86699081  0.60565972  0.48549687  4.94492815]
13420.58583155636
第542组系数
[-0.58939101 -0.13806971  0.02494495  5.74357887]
0.4806913332033754
第543组系数
[-0.27149321 -0.04524887  0.82036199  6.89208597]
0.41072548891790317
第544组系数
[1.18059001 2.09890932 0.61051698 8.85724432]
0.7038536701373591
第545组系数
[-0.9932646   1.38817869  0.80109966  7.5376921 ]
1.3946131253176381
第546组系数
[0.79563941 0.02722091 0.2137270

0.3104805576255638
第641组系数
[ 1.09048268 -0.34427798  0.22785104  7.1617272 ]
0.36337181795267776
第642组系数
[-0.21219395 -0.36011095 -0.17170747  5.56201312]
0.34178978104203184
第643组系数
[-8.22937264 -1.78860327 -7.88747079 -5.77272874]
1.835865000584535e+26
第644组系数
[1.79968077 0.80167598 0.11189146 7.63690263]
0.4587401010748705
第645组系数
[1.79962894 2.9257885  0.72022263 9.05102783]
0.659598298398375
第646组系数
[-0.44387755 -5.27040816 -3.84954912 -1.85052088]
1325504.0199339823
第647组系数
[ 1.6237993  -1.03521867 -0.22442033  5.92742346]
0.6131166211085879
第648组系数
[-1.27938895  1.27393219  0.87905102  6.52631004]
0.9361593008803738
第649组系数
[-0.89984676 -0.29288722 -0.28977788  4.64924811]
0.6734288325039501
第650组系数
[ 0.29127796 -0.70005021  0.39217862  6.84534002]
0.5117093014575267
第651组系数
[ 1.23579462e+01 -2.17522813e-01 -1.99802775e+16 -2.93710079e+16]
第651组系数
[-1.55777778  0.72133333  1.67894017  7.74997333]
2.813333382789929
第652组系数
[ 0.66030754 -0.47921567  0.11786154  6.8855482 ]
0.39644

0.2390149765036146
第745组系数
[ 6.65547264  2.89676617 -2.          6.78947761]
6.237944938736879
第746组系数
[ 1.31467732 -0.74810668 -7.29421386 -0.93730587]
37580283313.520294
第747组系数
[-9.11888277  2.60588197 -3.71316799  2.25327153]
6.853106908897787e+21
第748组系数
[ 0.73976245  1.75862069 -0.6894635   5.94062801]
0.7077860051639085
第749组系数
[ 0.62227905 -1.47368506  0.74965222  6.75157632]
1.2506062087020642
第750组系数
[1.08574561 0.68678363 1.15612573 8.12190132]
0.5602976989575646
第751组系数
[0.45866265 0.49617363 1.07053569 8.14857769]
0.4489895088935322
第752组系数
[ 1.64824834  0.01100094 -0.11627194  7.13816569]
0.39390168880923715
第753组系数
[0.70833333 1.54166667 0.04666667 8.19735   ]
1.1515264037700832
第754组系数
[ 1.4346355  -0.02430022 -1.30407817  5.05391558]
1.6597013473902684
第755组系数
[ 2.86676958 -0.28569958 -0.08765191  7.19434615]
0.5414149099270857
第756组系数
[ 1.65093168  3.46708075 -7.68015691  1.89577574]
1205930856719.6455
第757组系数
[ 0.70724506  5.29960978 -5.02891519  4.55558533]
48169001

6.8420953204131525
第849组系数
[0.48313436 0.22527505 0.17075261 7.13012571]
0.2969842901739429
第850组系数
[-2.18080015  4.24320446 -0.0330819   6.00599939]
9.976141934748094
第851组系数
[-0.26200436 -1.3224135   0.01380887  5.37283452]
0.873452234507566
第852组系数
[0.23024855 0.02987837 1.52573091 7.85014407]
0.5150608542478217
第853组系数
[-0.0351496  -0.13077611  0.10860859  6.07207517]
0.2702680507435592
第854组系数
[ 1.00559108 -0.39237174  0.68354495  7.76853585]
0.4959884927580889
第855组系数
[-0.13960659 -0.21743227  0.52826106  6.68627025]
0.35080805652549857
第856组系数
[0.38176172 0.79153139 0.70330797 8.0023279 ]
0.47286051093130266
第857组系数
[ 0.48810282 -2.07992656  2.20598044  8.98329749]
25.54459945358264
第858组系数
[1.26315333 0.04009047 0.5079938  7.73960332]
0.3877268298153959
第859组系数
[ 1.13228656 -0.90966784 -0.2364685   6.45295957]
0.6077604686130308
第860组系数
[-8.26027397  3.4109589   3.31506849  8.56931507]
29232696347539.37
第861组系数
[ 1.45751634 11.61111111 -5.19546328  6.28861669]
140572377.6515118

1.6747977725035439e+22
第955组系数
[-3.49692706 -9.06923362 -2.89892632 -2.73656275]
5888106495179.671
第956组系数
[-0.05593745 -0.10770321  0.15109933  6.36848245]
0.26147809670043093
第957组系数
[ 1.16777296 -0.73173123 -0.32257194  6.56646434]
0.6358404280511296
第958组系数
[ 0.41512958  3.98318935 -1.6595844   6.53869017]
32.443565515270954
第959组系数
[ 0.28635846 -0.71997068 -0.5737649   5.42043017]
0.5893893259580647
第960组系数
[ 0.76930053  0.61211776 -0.30469001  6.80449181]
0.4452521992759459
第961组系数
[ 1.69996104 -0.83364524  1.53488372  9.34450636]
1.5890439924151267
第962组系数
[ 1.28404634 -0.5719818   2.20259385  9.99901966]
1.7067692889100912
第963组系数
[ 1.19062076 -2.82290634 -0.40016597  5.75786015]
110.5542196123227
第964组系数
[ 0.15580622 -1.67728371 -0.54911748  4.48780775]
1.2117447162260462
第965组系数
[ 0.66902958 -0.05157663  0.40825668  7.53432617]
0.41682792684905023
第966组系数
[4.73713543e-03 2.50244328e-01 9.80825303e-02 6.98361282e+00]
0.6090713695636084
第967组系数
[-0.41202501 -0.02117126 -0.39333

63.22146135937044
第1058组系数
[ 0.69487976 -0.63497028 -0.75403269  5.76478823]
0.9546558026307229
第1059组系数
[ 0.56799783  2.06581828 -2.64125871  5.5290647 ]
1865.7993218226688
第1060组系数
[0.0728022  0.6796398  0.59350834 7.10696886]
0.385803653207101
第1061组系数
[ 0.38573924 -0.56959987 -0.03091736  6.64723481]
0.5893444143736157
第1062组系数
[-0.07385399 -1.14728353  0.21028899  5.99400579]
0.7570852509466155
第1063组系数
[0.13748666 1.07629535 0.80441451 8.26524573]
0.708064106966372
第1064组系数
[0.34661525 0.18123393 0.73376883 7.77773832]
0.4411324063882385
第1065组系数
[ 0.75377747 -0.66620879 -0.10463562  6.47666966]
0.4159161892679666
第1066组系数
[-0.06004306 -3.78016129  0.15718483  5.75680201]
9671.442156121197
第1067组系数
[-0.48601667 -1.81517176 -2.00756814  3.33558151]
144.04989174711807
第1068组系数
[28.4010989  -7.18406593  2.33791209 15.96387363]
60908939688361.59
第1069组系数
[ 1.38544304  0.04757384 -0.05806962  7.18956593]
0.3757627262702892
第1070组系数
[-1.43307374  0.4097763   0.02667771  4.69729876]
0.9

0.29042295838004906
第1162组系数
[ 2.18161973  1.73302772 -2.23750273  5.81257149]
90.01955535263534
第1163组系数
[ 1.06003067 -0.64039311 -0.66602978  5.91387592]
0.6599080642937755
第1164组系数
[ 1.11809083 -0.39089393 -0.17566912  6.46707271]
0.35466884701107004
第1165组系数
[ 5.5330824  -5.31724853  2.07147237 12.56682307]
1436183620.939375
第1166组系数
[ 0.23523524 -0.55355355  1.75680681  8.04179029]
0.6711089646278185
第1167组系数
[ 3.62345679 -0.9691358   1.05234568  8.83275062]
0.9737004280299881
第1168组系数
[ 0.09030285 -0.25972724  0.47603472  6.52037718]
0.3367570983007487
第1169组系数
[ 1.18612828 -0.06872837 -1.31513715  5.83702299]
4.286438053545274
第1170组系数
[-0.09222697 -0.16549271 -0.16314479  5.86001263]
0.3018528291441649
第1171组系数
[-1.24795726  4.33224387  1.36666667  8.5206763 ]
1.559579055227624
第1172组系数
[-0.02561234 -0.08283633 -0.07206574  5.82091291]
0.2947095054635806
第1173组系数
[-0.18166728  0.09166362  0.5869327   7.16813784]
0.5005685290585641
第1174组系数
[ 0.86205708 -0.42836916 -0.99354484  

120662.96645137403
第1268组系数
[-0.51749994 -0.3627908  -2.17834095  2.16404405]
56.21008231857625
第1269组系数
[-0.13302752  0.29357798 -0.24132429  5.89658357]
0.3741867539691686
第1270组系数
[ 0.57972995  0.20308515 -0.77220738  6.46446951]
1.730285571633881
第1271组系数
[ 0.17917369 -0.34106239 -0.36382799  5.91969646]
0.43495685083179875
第1272组系数
[1.93478261 0.07880435 0.05908584 7.39741848]
0.41593425787745614
第1273组系数
[ 0.23162135 -1.43303122 -0.70970124  5.21452367]
1.876101093863957
第1274组系数
[ 4.42564013  0.14801824 -4.40488717  4.46481936]
409667.046689626
第1275组系数
[-0.05971244 -0.05859307 -0.14388946  6.06728315]
0.3190078959285459
第1276组系数
[ 9.56565657  8.02020202 52.10673401 89.85730303]
3.762945787519009e+27
第1277组系数
[ 1.10107847 -1.33330798 -0.03539648  6.59235819]
1.1605609285547902
第1278组系数
[-11.54963876  -1.14994898  14.4678395    7.76922634]
1.4652739881292794e+16
第1279组系数
[ 0.16758062  0.22543921 -0.07164057  6.44166848]
0.2697194463246991
第1280组系数
[ 0.0128294  -0.05513176  1.0002

0.37835106441458594
第1374组系数
[-0.35003133 -1.60425342 -0.00827236  5.51773382]
2.072696976352432
第1375组系数
[ 0.51265784 -0.13651779 -0.09176527  6.58057957]
0.2767423549791968
第1376组系数
[ 1.44235294  2.27764706  2.18164706 11.08412706]
1.266098307508237
第1377组系数
[ 0.13354864 -1.98036188 -0.28675105  4.57859471]
2.1351849186857264
第1378组系数
[-2.27480916  0.77633588  0.76656489  6.03576641]
13.960929734235826
第1379组系数
[ 0.35220289 -0.13877207  0.15662057  6.69148153]
0.24274042562610978
第1380组系数
[3.24635607 1.25446547 1.02628929 9.36166905]
0.6550299384386801
第1381组系数
[0.64660875 0.08590329 0.11536109 7.23515795]
0.3808076437539969
第1382组系数
[-0.2503773  -0.01775516  0.16950256  6.2316388 ]
0.3005247259375742
第1383组系数
[-0.20148469 -0.02746025  0.1275632   6.28280499]
0.3055300259137718
第1384组系数
[ 1.48797901 -1.34243104 -0.11528242  6.84521914]
1.4262736184756057
第1385组系数
[0.46119553 0.35134095 0.25061341 7.15747379]
0.2867354109653104
第1386组系数
[ 0.12486716 -3.59431456  0.38049947  6.38878693

0.5855514842326712
第1476组系数
[-0.06977964 -0.36883526 -0.19921224  5.74949251]
0.33621828498461703
第1477组系数
[ 0.35439055 -0.06570182  1.1010244   8.07967352]
0.5634927347377876
第1477组系数
[ 2.39464763  2.90424974  1.34268789 11.37721923]
2.007998868120214
第1478组系数
[1.1303583  0.06802859 1.09203711 8.23110666]
0.4751495241086539
第1479组系数
[-0.16326832  2.39517743 -0.12511374  6.35300154]
0.5459492097500667
第1480组系数
[0.6838066  0.09330117 0.68112415 8.13877031]
0.663699145781852
第1481组系数
[ 0.69719966  0.02791026 -0.46643531  6.34630029]
0.4761079642524848
第1482组系数
[-0.91060291  0.49249249 -1.48617849  3.73477477]
14.799157683910314
第1483组系数
[ -0.58226061 -13.13686571   1.64105971  -2.23819865]
1.0496569202335962e+20
第1484组系数
[-0.50595952 -0.76465735 -1.23524671  3.24871343]
2.3333462940705085
第1485组系数
[ 0.1556972  -1.06291628 -0.16111987  5.89251604]
0.7464744963381813
第1486组系数
[-1.8195813  -5.99481011  0.76789284  4.84458709]
190066504.49101794
第1487组系数
[-6.02145861  4.93333333 10.8292301  

0.903639778990979
第1578组系数
[ 0.66279098  0.04809313 -0.18168677  6.68607907]
0.3229810087771662
第1579组系数
[ 0.60215054 -0.43010753  0.06981882  6.57136544]
0.2972269802584192
第1580组系数
[0.63057672 0.64991208 2.25369737 9.86499659]
0.9414765587666776
第1581组系数
[-0.76163992  0.85141483 -0.04118598  6.48062831]
1.2069933548230707
第1582组系数
[ 3.90909091 11.36363636 29.07727273 45.15495455]
11447035245.53421
第1583组系数
[-0.66451131  2.09512896 -1.0818592   4.42183782]
2.0632126607036603
第1584组系数
[-0.08778654 -0.36424793  0.12259973  5.83192842]
0.32930848790249273
第1585组系数
[  2.8        -22.36666667 -16.67777778 -22.027     ]
6.983175374687994e+40
第1586组系数
[-0.18242474  0.26720911  0.37070789  6.6318991 ]
0.3189132072738117
第1587组系数
[ 0.0741421  -0.24409466 -0.11045215  5.87636548]
0.2632560813335221
第1588组系数
[-1.05563123 -3.63723971  0.92236313  5.24178782]
2723.205845883247
第1589组系数
[ 0.8481755   1.24522945 -0.09473627  7.41446224]
0.5170664815485577
第1590组系数
[-8.19641577e-01  9.37847312e+01 -1

0.35692738560096055
第1683组系数
[  6.94827586  -3.94360632 -12.08872126  -8.59523707]
8.470023427950704e+16
第1684组系数
[ 1.5302391  -3.98171589 -0.40486704  5.51224348]
17154.219157292715
第1685组系数
[-0.22625929  1.32617671 -1.00604459  5.29881057]
2.0957741256902067
第1686组系数
[  5.83715596 -10.2942879    1.09174312  10.44329893]
1.8441800979772344e+19
第1687组系数
[ 0.22294248 -0.05886862 -0.26970531  6.02580976]
0.29473293981462056
第1688组系数
[ 0.57379241  0.99615577 -0.78284134  6.15101697]
0.9825139340576733
第1689组系数
[ 0.28894917 -0.10604884 -0.01894283  6.59972827]
0.2948322580889348
第1690组系数
[ 0.31678524 -0.05302556 -0.22848096  6.30356501]
0.3109874364868279
第1691组系数
[ 0.0657127  -0.05652829  0.45020203  7.20021673]
0.4865337351536876
第1692组系数
[ 0.431749   -1.96932803 -0.56737298  5.31776809]
4.641975353313501
第1693组系数
[ 1.6745182   0.18797797 -0.1178342   7.19216152]
0.39873924347712997
第1694组系数
[ 1.7396142  -0.59418812 -0.42141086  6.73913894]
0.6408546961679351
第1695组系数
[  1.78967689 -15.0

0.2835246570373269
第1789组系数
[ 0.86298259 -0.90264951 -0.79031037  5.19945647]
0.7152116995647082
第1790组系数
[2.47459207 0.41042685 0.04688827 8.15032209]
0.622540490695974
第1791组系数
[0.3598801  0.46639063 0.08963039 6.98058772]
0.3002834692007791
第1792组系数
[-0.08769109  0.3278775  -0.41527549  6.054169  ]
0.642414187530165
第1793组系数
[0.96281497 1.46784172 0.53268691 8.57180467]
0.6925046528518792
第1794组系数
[ 2.71695421  4.10273299 -1.0434376   8.85492059]
4.921750794819317
第1795组系数
[ 0.92575955 -2.39290481  0.06401724  6.47126159]
28.058378800203485
第1796组系数
[-1.10428957  1.22067719  0.11058206  7.2706395 ]
3.9152597095764485
第1797组系数
[-0.80509066  4.96025105  1.85913529 11.41930265]
8.194207117088482
第1798组系数
[ 1.79202279 -1.49667616 -2.77359924  3.6514416 ]
493.8428259028276
第1799组系数
[ 11.5        -30.3686821    4.62328767  12.21813651]
2.981693702467603e+62
第1800组系数
[ 2.59451394 -2.14661999 -0.68323195  6.67319121]
13.060705089814961
第1801组系数
[-0.37478067  0.21276596  0.93854411  7.076897

909145062636940.8
第1892组系数
[ 2.32310972 -0.1469895   0.09205272  7.57330783]
0.4768931749049087
第1893组系数
[ 1.27375855 -2.23016182  0.11644331  6.50516933]
12.461412334655781
第1894组系数
[ 0.496242   -0.12742341 -0.48549065  6.18695105]
0.5380522573484072
第1895组系数
[0.1    0.45   0.95   7.7855]
0.438268377709147
第1896组系数
[0.24325353 1.0009813  1.07208752 8.25387518]
0.513172931973097
第1897组系数
[0.09717317 0.24670142 0.54688976 7.05709278]
0.30970332184320015
第1898组系数
[ -0.9726776  -13.75956284  -1.34663816  -0.45398432]
9.393536996540804e+22
第1899组系数
[-6.96463472 -2.07590133 -3.17675522 -1.95160484]
998832291570972.8
第1900组系数
[ 0.57329331 -0.24929168  0.29427065  6.9731661 ]
0.2930468614628458
第1901组系数
[0.62502155 2.0640672  0.0850248  7.57638111]
0.529704458307817
第1902组系数
[ 2.83333333  4.94444444 -0.88319088 10.75277778]
17.300371121467162
第1903组系数
[-0.3922531  -0.45520402 -0.03333333  5.39126552]
0.3810884464195664
第1904组系数
[ 1.48221626 -1.71170688  5.82394996 12.13809473]
10.225448527271

0.31727269112671774
第1996组系数
[-1.62811449  0.86758281  1.20597347  7.99110943]
6.746464541206145
第1997组系数
[ 1.65644154  0.27426825 -0.05162229  7.28122802]
0.3953694760787275
第1998组系数
[0.69620212 0.06642651 0.18433678 6.95630842]
0.28041884463282524
第1999组系数
[-4.76495794  6.66854468  2.37065545  8.22743057]
515818.9717215731
第2000组系数
[-1.87605388  0.71267627 -0.4136602   4.44779365]
6.065454440360172
第2001组系数
[  5.49071499 -10.27617801   2.66320353   9.46675352]
2.458706332872868e+18
第2002组系数
[ 8.23516287e-02 -4.28849377e-03  9.61901421e-02  6.40998288e+00]
0.2259620416912365
第2003组系数
[ 0.53069099 -0.00942645 -1.11032767  5.94054093]
3.8003317846210836
第2004组系数
[ 0.20452287 -0.74158172 -0.02870496  5.91373036]
0.3570489533931451
第2005组系数
[0.03608638 0.31259077 0.67632759 7.36346372]
0.3705148902068069
第2006组系数
[ 0.68511224 -0.38987629  0.08842803  6.74692211]
0.30883921198504716
第2007组系数
[ 2.89189189  3.20833333  1.23064136 11.32081993]
1.6057830603007914
第2008组系数
[ 1.67950864 -1.33441

0.38646640482667016
第2101组系数
[0.03064904 1.96394231 0.3588742  7.64972656]
0.5868813986304111
第2102组系数
[ 4.37708289 -0.77048619  0.51355751  8.50265839]
0.819658426064346
第2103组系数
[-1.01637743  1.41087543  0.3101864   6.31096205]
0.7981741338335043
第2104组系数
[ 1.90909091  1.68181818 -3.37632135  3.13817125]
2215.0617878738026
第2105组系数
[-0.39085732  0.04655375 -0.54816602  4.97226001]
0.6059328589467656
第2106组系数
[ 1.43262574 -2.55109326  1.70887996  7.73118531]
47.74138202768434
第2107组系数
[0.21112372 0.19353008 0.3        6.97759478]
0.27031518959249007
第2108组系数
[ 2.89571308 -2.05989297  1.07604632  9.20481691]
24.87384538731215
第2109组系数
[ 0.93449251 -1.50420251 -0.42283348  6.34060854]
2.52960137363516
第2110组系数
[ 0.93987322 -1.39395606  0.4559189   6.86774751]
1.194882816463041
第2111组系数
[-0.30135847 -0.01298161  0.39758533  6.27901755]
0.34009993491695467
第2112组系数
[-0.29773491 -0.13900195  0.12281012  6.0382888 ]
0.3124625599944697
第2113组系数
[-0.22787551  1.98511502  0.6373207   7.5446530

3.3774597336388745
第2205组系数
[ 0.30258718 -0.48973566  0.53152418  6.88192548]
0.36564094951355436
第2206组系数
[0.66982473 4.65324491 0.72240644 9.08669351]
0.8322063557869818
第2207组系数
[ 0.83701565 -1.85822138  1.97328744  8.44490041]
6.676077089564927
第2208组系数
[ 1.93237971  1.40182055 -1.93929138  5.47356485]
19.43839851775339
第2209组系数
[ 0.29636722 -0.10292311 -0.15472694  6.05242141]
0.2749304943179381
第2210组系数
[ 0.50774084 -0.053923    0.07664895  6.59768184]
0.25834578391082824
第2211组系数
[-0.68391527 -2.37527807  1.35603056  7.22623271]
49.52738148939942
第2212组系数
[ 1.14971223 -4.93357528 -5.03306573  0.16678434]
324318926.60671747
第2213组系数
[ 2.64498618 -0.04889459  0.73537308  8.68013304]
0.6245153817125987
第2214组系数
[0.79483777 1.13649289 0.06445498 7.91430711]
0.7669218746003609
第2215组系数
[ 2.1117151  -0.04843543 -0.20266221  7.02288592]
0.4476778368984429
第2216组系数
[-0.04668998  0.08184551  0.08822627  6.44095895]
0.27374009536147514
第2217组系数
[ 1.51531992 -0.94628016 -0.05012516  6.5931

0.6573672285515473
第2309组系数
[ 1.02453826 -0.91029024 -0.15963061  6.39735884]
0.5378302567590876
第2310组系数
[ 0.70020068 -1.68109244  0.76598456  6.50103656]
1.6433609337409483
第2311组系数
[ 0.11279809 -0.05525092 -0.18205922  6.25705152]
0.345976624029656
第2312组系数
[ 0.28770292 -0.17591703  0.0370143   6.64708754]
0.3031884036404246
第2313组系数
[ 0.13513915 -0.02327816  0.10417405  6.48231901]
0.22516552285931585
第2314组系数
[-1.55244755  6.30769231  0.64080364  8.05850594]
2.51561399792887
第2315组系数
[ 0.23068139 -0.05633803 -0.40557874  6.02236194]
0.42386262032299293
第2316组系数
[-1.67833074 -9.63426646  2.92560912  0.73980819]
31571638148382.055
第2317组系数
[ 2.21970401 -0.40541848  0.05976116  7.38754953]
0.4941673129691678
第2318组系数
[0.35332748 0.17873584 0.24151135 7.24730303]
0.38648199139651973
第2319组系数
[  4.10441001 -10.37568534   8.28390942  17.94915137]
6.685641800546264e+20
第2320组系数
[ 0.53759833  0.82950023 -0.20205923  7.27646946]
0.7697673587248326
第2321组系数
[-2.08838545  7.79020421  0.73978

0.45437555305414395
第2412组系数
[-0.59426129 -0.94249084 -1.3982092   3.57280708]
7.823191046774383
第2413组系数
[-0.12571964 -1.48775722 -0.44134214  4.81891595]
1.1438734371197452
第2414组系数
[-0.42114726 -1.25701048 -0.14079734  5.20375609]
0.9707431258009612
第2415组系数
[ 4.68669866  2.99798857 -0.33875597  8.7755365 ]
0.7849711841544024
第2416组系数
[0.49539334 1.04606662 0.04394047 7.19111269]
0.39375238983095145
第2417组系数
[ 0.7323406  -0.21038723 -0.61394242  6.54968255]
1.2569296479345085
第2418组系数
[ 0.77255504 -0.43405718  0.30450024  7.08803847]
0.36784264240864983
第2419组系数
[-5.00173767 -3.50110851 -0.68413326  2.28832554]
32519719.927861985
第2420组系数
[-2.14045141  6.99064082 -7.2905485  -0.80990386]
3588002551495.437
第2421组系数
[-0.62024838  0.22311221  0.1244423   6.02658282]
0.49317831706981663
第2422组系数
[-0.37503068  1.32971001  0.19844431  6.69902949]
0.4935652712751132
第2423组系数
[ 29.05263158  -5.89473684 -41.33958183 -31.72310022]
5.818534728903345e+68
第2424组系数
[ 1.55627399 12.08473086  0.086

0.2999366270469991
第2517组系数
[ 8.44448294 -3.34287199  0.09197991  9.10410566]
6485.170158684537
第2518组系数
[-1.90196472 -0.09933463  0.78002668  6.11578288]
5.474164845608206
第2519组系数
[-0.12342157 -0.69134314 -0.95604902  4.07577549]
1.010023838895022
第2520组系数
[ 0.28502617 -0.38582897  0.52173468  7.11168333]
0.4007449222676872
第2521组系数
[-1.08876301 -0.68470793  3.71428571  6.89929209]
0.908842907252377
第2522组系数
[-0.51914894  2.76170213  1.80851064 10.02012766]
2.369489661958046
第2523组系数
[0.06472442 0.15427907 0.0104712  6.11558834]
0.30227451444979175
第2524组系数
[ 0.89295653 -0.36301755  0.01234665  6.80917689]
0.3291149764599825
第2525组系数
[ 1.67038372  0.14852812 -0.93524174  6.80846421]
1.868254214813777
第2526组系数
[ 12.          14.27285513 -18.68495077  -7.06136428]
2.807999202457513e+29
第2527组系数
[ 1.44280173 -1.78918028  0.8397889   8.19682717]
7.386006297104362
第2528组系数
[ 0.60271743 -0.76715832 -0.39985276  5.79270181]
0.46005194687811535
第2529组系数
[0.81687364 0.47990435 0.93856352 8.33

14.492104358583687
第2621组系数
[-0.26352705 -4.84168337  1.34418838  7.07111723]
2638540.1210533213
第2622组系数
[-1.10841394 -2.78306612 -1.17912636  2.15926779]
20.957778539526387
第2623组系数
[ 0.62720827 -0.36648161 -0.08294655  6.57832593]
0.3210143017012577
第2624组系数
[30.51352232  0.45454545  0.52297165 18.94546758]
211.36184539323693
第2625组系数
[ 3.05621622 -6.76540541 -1.90378378  3.65791351]
4292814594.750803
第2626组系数
[ 0.36983666 -0.51962648 -0.26098683  5.93422304]
0.33511826306423603
第2627组系数
[0.55427252 1.31408776 0.047806   7.28336952]
0.4291465967511393
第2628组系数
[ 0.34207641 -0.25333548 -0.14        6.34283479]
0.29494032152349975
第2629组系数
[ 0.97273035 -3.29574864 -0.10017785  5.93194639]
981.5775677166024
第2630组系数
[ 0.29546921 -0.36194417  0.71596016  7.23123658]
0.3932413414278711
第2631组系数
[ 1.39267767 -2.86241107 -1.83752853  4.07457184]
104.34128242864506
第2632组系数
[ 150.7     354.5    -304.91      3.8713]
第2632组系数
[ 2.16022639  0.84016393 -1.71252927  6.18898126]
13.08396310634170

0.39372845297659914
第2725组系数
[-0.61561613  1.71135718  1.14826803  8.17797104]
0.9508402363978359
第2726组系数
[0.45215256 2.54713038 1.90106861 9.54840819]
0.7435624597331465
第2727组系数
[-0.00800594 -0.17936247  0.55981477  7.03354132]
0.40239314707503415
第2728组系数
[-1.55168462 -2.77389411  5.98617923 11.50570112]
1444.9724074762594
第2729组系数
[0.61647988 0.21218109 0.10574175 7.17468349]
0.32546846022986986
第2730组系数
[ 0.2549025  -1.0730358   0.56173773  7.1727689 ]
1.3030608611977694
第2731组系数
[ 1.27420671  1.77200967  1.22970454 10.23528157]
1.6187003366782797
第2732组系数
[ 0.023763   -0.18564562  0.72094199  7.23263122]
0.4308782047034068
第2733组系数
[ 0.59261994 -0.18463447 -0.80408428  6.08436218]
1.4049044113925393
第2734组系数
[6.72247858e-03 4.83811590e-01 1.99422742e-01 6.94779226e+00]
0.37674946584920427
第2735组系数
[ 0.9462572  -1.23800384  0.86251841  7.7340441 ]
1.439181679084484
第2736组系数
[ 0.91799902 -0.42809086 -0.10097517  6.65031353]
0.34936944195238323
第2737组系数
[0.69465533 0.84467051 0.067

0.4742677441704333
第2830组系数
[ 4.43197871  0.28902561 -0.5069207   7.97443225]
0.7918334164316199
第2831组系数
[ 1.32175199 -0.31411911  0.13607892  7.17560985]
0.37867231192613665
第2832组系数
[-0.48825669  2.02181315  0.74992745  7.55704521]
0.6477647461965722
第2833组系数
[10.24934383  2.01312336  2.42519685 15.74958005]
6.347450073985137
第2834组系数
[ 0.85734665 -1.82414732 -0.56403496  5.64174009]
3.2412025973555987
第2835组系数
[ 0.31234559 -0.55864277  0.57911071  7.30047155]
0.6180339087268989
第2836组系数
[-0.36633663  2.5049505   0.33644685  7.55111153]
0.7864415594098886
第2837组系数
[-0.13451571 -0.69448154 -0.03388647  5.48866014]
0.3752143629099001
第2838组系数
[ 1.67720514 -0.94187225  1.37911457  9.16472136]
1.7565352591618326
第2839组系数
[ 1.04037923 -0.33452356 -0.38239411  6.37787936]
0.4104297982888501
第2840组系数
[ 0.56311911 -0.56871208 -0.21137377  5.92929264]
0.34518758654477255
第2841组系数
[ 0.60338022 -0.75767879 -0.37087155  5.74886789]
0.43043782937660785
第2842组系数
[ 2.38228942 -8.14470842 -5.144457

0.28759328222409475
第2934组系数
[ 0.40457606 -0.04247181  0.12243285  6.89922001]
0.2858258305867953
第2935组系数
[ 2.68935351  0.83627659 -0.30773678  7.21356547]
0.5859060060635775
第2936组系数
[ 0.26674299 -0.94668584  0.9060413   7.21325561]
0.7543235942663136
第2937组系数
[2.16867712 0.83293124 0.04168342 7.80922799]
0.49275715224668903
第2938组系数
[ 0.13520063  0.10692922 -0.06567553  6.37863686]
0.25735682028993134
第2939组系数
[0.39043954 0.75313707 0.09644745 7.08788693]
0.3390294367032157
第2940组系数
[ 2.14603264  2.57618881  0.68343722 10.11549352]
1.388717906182951
第2941组系数
[ 4.47224768 -9.69518272  3.28961889 10.48997852]
2.7747288396373936e+17
第2942组系数
[0.11415213 0.7806497  0.28548727 6.75626367]
0.37428445223665335
第2943组系数
[ 1.70977242 -2.25745653  0.046263    6.31811311]
10.216366847046237
第2944组系数
[ 0.12843669  2.50092713  3.55895886 13.27495742]
9.132583326336873
第2945组系数
[ 0.40301622 -0.53058311  0.27914638  6.92720854]
0.4528125492019097
第2946组系数
[ 0.02354811 -0.47555413  1.55800347  7.74

361.7085559348386
第3039组系数
[ 0.5393723   4.75643676  2.29430558 11.97335651]
2.845017530532061
第3040组系数
[ 0.30725158 -2.0687381   0.80363917  6.69490359]
7.696167530189078
第3041组系数
[ 2.56230168 -2.0953892  -1.14191587  5.43457072]
5.604021885873726
第3042组系数
[ 0.09861391  0.09244876 -0.21033692  6.02940276]
0.29298431458484353
第3043组系数
[0.5        5.29726891 0.36397059 8.12043592]
0.7083678797051949
第3044组系数
[-14.18620641  -2.01564583  15.01648776   7.82792254]
6.43569979781704e+21
第3045组系数
[ 0.36389646 -0.49577657 -1.54844934  4.57210855]
8.915013293918006
第3046组系数
[-6.99712203e+00  1.17740023e+02 -1.49161550e+01  2.92709133e-02]
4.019429260757493e+30
第3047组系数
[-1.37086173 -2.34359342  1.034903    5.74975203]
21.334853554595714
第3048组系数
[ 3.66562043 -2.91083211 -1.08849021  6.65665442]
326.899627695114
第3049组系数
[ 0.89943882 -1.12467641  0.28265893  7.00309797]
0.9370016578759708
第3050组系数
[-0.21074869 -0.07721345 -0.00853717  5.75705581]
0.3105915324162036
第3051组系数
[ 0.10406194  0.33108

0.5302698826819073
第3142组系数
[-0.41935484 -0.13793103  0.68358973  6.76644532]
0.489608301609005
第3143组系数
[ 2.03901009 -0.03896812  0.60523352  8.24256955]
0.5217816852590048
第3144组系数
[2.22906122 7.06987755 0.58632653 9.60696531]
0.8244133007454303
第3145组系数
[-1.77577593e-01 -2.05584176e-01  2.66462223e-04  5.81245063e+00]
0.28321861253423564
第3146组系数
[-0.31320926  0.01363642  0.0504749   6.08095048]
0.3376478232598673
第3147组系数
[ 0.22697627 -0.38159244  0.26399765  6.77649598]
0.35985104469299967
第3148组系数
[ 0.94581953 -0.48119275  0.61060451  7.36760423]
0.42662842945389456
第3149组系数
[0.72326146 1.08234133 0.72142423 8.30407668]
0.503237674967205
第3150组系数
[-0.84570312 -0.8046875  -0.07470703  5.92806152]
2.3208845790425037
第3151组系数
[ 0.48293952 -0.71601994 -0.53474962  5.5363321 ]
0.508450511670802
第3152组系数
[ 0.70878604 -0.42371406 -0.10868919  6.53416319]
0.330591952686403
第3153组系数
[ 1.03649301 -0.35869155  0.01887036  6.86666859]
0.3399220682403687
第3154组系数
[0.41005734 0.0945969  0.0073

721.6107113549955
第3248组系数
[ 4.11488673 -2.26860841 -0.28511327  7.74983172]
27.165396197052658
第3249组系数
[-0.10285195 -0.05470649  0.03417753  6.09249774]
0.25144117807434374
第3250组系数
[ 2.06593438  0.25467329 -0.62893206  6.90415147]
0.679269672675679
第3251组系数
[ 0.38686764 -0.17463617  0.6173388   7.52831968]
0.4605547866511164
第3252组系数
[-0.13060646  0.10342208 -0.02199519  6.14156693]
0.284339987537442
第3253组系数
[1.01350791 0.47770561 0.85783873 8.16054089]
0.4322101409140725
第3254组系数
[1.26515152 0.59900731 0.02771682 7.52434352]
0.4217434805256404
第3255组系数
[ 14.69285129 -24.66745186  -8.72664891  -0.19772839]
1.5345687899700627e+48
第3256组系数
[ 2.03779201 -1.11585887 -1.17316586  6.04891367]
2.8489157951792072
第3257组系数
[-0.08002843 -0.39104478 -2.35289268  2.97786183]
153.31014841446196
第3258组系数
[ 2.0654961  -1.36840703 -0.34040154  6.65543495]
1.2665949089031596
第3259组系数
[ 0.33041432 -0.69441903 -1.35779637  4.89702392]
5.9389526829705686
第3260组系数
[-7.61538462  6.71623932  1.66666667  

0.24321050329259916
第3353组系数
[ 3.1211271  -5.2799409  -0.36430636  5.77963733]
8645256.188404756
第3354组系数
[-5.59586406 -1.66925342  1.85633827  4.56804617]
21003168.50912063
第3355组系数
[0.21028639 0.55078773 0.98346446 8.18293979]
0.5679507616189863
第3356组系数
[ 11.27319149 -13.3787234  -14.98144681 -11.70733957]
1.2444345024963635e+29
第3357组系数
[-0.36076173  0.17830054 -1.15780911  5.16780373]
5.875699882056702
第3358组系数
[ 0.02534599 -0.7129868   0.42531113  6.51848865]
0.46221206235925427
第3359组系数
[-0.62600544 -0.07537698 -1.92458119  3.68256145]
80.2526058548778
第3360组系数
[ 0.64161078  7.53408067  3.59366763 15.38243553]
16.833801637208182
第3361组系数
[ 0.18540815 -0.52384822 -0.26349825  5.89857379]
0.38358736515014674
第3362组系数
[ 0.76759062 -9.15636105 -1.41748401  2.40830277]
166044695177323.72
第3363组系数
[ 0.99001363 -0.37681159  0.22098295  7.05660743]
0.3506347014151397
第3364组系数
[ 0.11250525  2.50713986 -0.0897732   6.60205743]
0.5420817915690719
第3365组系数
[-0.02865177  0.12521355  0.112507

1.6984420174815047
第3458组系数
[-0.13385315  1.47433398  1.47270955  8.42283626]
0.6316897660922964
第3459组系数
[ 0.94075039 -0.51192317  0.12678441  6.8399777 ]
0.36331410401907593
第3460组系数
[ 2.64705009 -5.85066362 -3.61747677  1.12891357]
14271170.65551012
第3461组系数
[ 6.07425743  7.76732673  1.74817047 14.83961257]
3.6466744380757037
第3462组系数
[-0.31860835 -0.46049158  0.01377705  5.59415128]
0.3538938759218096
第3463组系数
[ 6.85228789 -7.8437917   0.31182796  9.55668845]
55060335989412.016
第3464组系数
[ -8.25777581 -10.38785999 -23.68418254 -34.60054852]
4.800375404107908e+49
第3465组系数
[ 2.56228225 -0.2841967   0.11489805  7.64514164]
0.5210203217593443
第3466组系数
[ 0.35501647 -1.51889233  0.60026772  7.02667649]
2.4003782452628926
第3467组系数
[ 0.52215521 -0.97515438 -0.67487631  5.39206313]
0.8072453340124573
第3468组系数
[ 0.54455156  1.11013731 -0.8066024   5.4886357 ]
0.7708218199241871
第3469组系数
[1.12809827 0.34745256 0.0704474  7.26691488]
0.34079594545271047
第3470组系数
[0.60297483 0.15331808 0.0227917

0.5041645276057722
第3563组系数
[0.45372275 0.17057449 0.02959827 6.74133612]
0.2512567177258709
第3564组系数
[ 0.48378964 -0.96857986  0.05575774  6.61982951]
0.807179019027287
第3565组系数
[-0.1019997  -0.03198543  0.39718221  6.38313291]
0.32322378918636857
第3566组系数
[-0.06208537 -0.29688321 -0.24904243  5.64266391]
0.3249932737403949
第3567组系数
[-1.34864303  9.63654196  1.0921034  12.21451948]
36.21799494521626
第3568组系数
[-1.09040177 -0.20120805 -0.04210758  4.91119229]
0.7381611634618556
第3569组系数
[ 1.25424905 -0.8122095  -0.71024627  5.98078293]
0.8323622767706971
第3570组系数
[ 1.26898734  2.66033755  2.56940928 11.78374051]
1.8354361989283918
第3571组系数
[-3.92663466  1.79407835  1.26957852  7.53120002]
60269.18304756515
第3572组系数
[ 0.51628294  0.65684641 -0.42617389  7.00237776]
1.0539371742709391
第3573组系数
[-0.06126068 -0.36875957  0.13852919  5.95327014]
0.2998201252898961
第3574组系数
[ 0.10554877  1.39577237 -0.01909254  7.39180442]
0.8288822108240892
第3575组系数
[24.66741796  2.48628897 35.25004269 64.99

0.48093556330666726
第3668组系数
[ 1.0600823   0.64197531 -0.72433726  5.85877156]
0.6472373907422565
第3669组系数
[ 3.11777321 -0.33329128 -0.29910433  7.14361393]
0.5669195522141194
第3670组系数
[-0.21900558 -0.03087415  0.06313341  6.18872813]
0.3159237138811464
第3671组系数
[ 27.60067085  -7.53642384 -18.92603423   6.80067343]
2.7104033881270612e+37
第3672组系数
[-1.65488404  1.93662913 -0.21026198  6.327615  ]
7.2598488663792455
第3673组系数
[-0.44203503  0.0558799   0.54136781  6.64172394]
0.4437068114778349
第3674组系数
[ 2.10638298  0.4893617   4.69893617 13.05201064]
2.3440046109455674
第3675组系数
[0.72407536 1.11877506 0.77376285 8.10274894]
0.4520799515594821
第3676组系数
[ 0.04447655  0.21965154 -0.79610945  5.82264713]
1.5634110234510112
第3677组系数
[ 0.11335862  6.56075291  2.70290771 11.59048462]
1.5609192545520176
第3678组系数
[-0.12718601  0.99761526 -1.61516989  3.98777498]
8.011135616761576
第3679组系数
[ 0.26493325 -0.01216967  0.86053664  7.23387904]
0.3861841888834533
第3680组系数
[ 0.26290293  0.64006416 -0.0782

67148.98730780999
第3771组系数
[ 0.0590835  -0.13352821  0.2810896   6.4882295 ]
0.2549776785301272
第3772组系数
[ 1.68228414 -0.14765738 -1.05539732  5.86972838]
1.1640195338399564
第3773组系数
[-0.15523617 -0.02504468 -0.41863126  5.6229912 ]
0.48483291198288025
第3774组系数
[-4.78982056  3.18190322  1.00637809  3.97817884]
110381.71525727953
第3775组系数
[-0.00651583  0.71850435 -0.16172998  6.48040201]
0.4393685123261927
第3776组系数
[-0.02703694 -0.0913551   0.03060518  6.20800215]
0.24251937844678548
第3777组系数
[-0.57665646  0.63372562 -0.07151378  6.06322231]
0.5940699421606964
第3778组系数
[ 0.97692308 -0.9439946   0.05330634  6.94088124]
0.814074432502875
第3779组系数
[0.28798058 0.93480906 0.15752632 7.42572597]
0.5128549061649854
第3780组系数
[ 0.21045846 -0.68164237  0.13998027  6.17820887]
0.35043680530132754
第3781组系数
[ 1.04440481 -4.52510031 -0.759144    5.50836594]
336947.4241414743
第3782组系数
[ 9.93900233e-01  5.41087107e-03 -7.70099635e-02  6.95987454e+00]
0.3264183145499817
第3783组系数
[0.75853295 0.56882169 0

0.4246984844770519
第3874组系数
[-0.15585092  0.2489536  -0.621072    5.10202684]
0.6124416066225781
第3875组系数
[ 0.17496994 -0.34235436 -0.50550516  5.54135709]
0.4477897388233037
第3876组系数
[ 2.42711599 -1.86363636 -0.90945542  5.13242655]
1.7904289060975223
第3877组系数
[ 0.31517094 -0.31232194 -0.81803458  5.22698786]
0.7976375641830304
第3878组系数
[0.25031131 0.13202679 0.19839461 6.73237105]
0.24336730657794003
第3879组系数
[-0.61582022  0.23050884 -1.77691221  3.50454893]
28.847604813671904
第3880组系数
[-0.00899471  0.53975552  1.82642401  8.56704946]
0.6366940068893969
第3881组系数
[ 1.41905855 -3.8576349  -2.23244546  2.83788037]
2853.747508449241
第3882组系数
[ 0.96068445 -0.38828062 -0.13322523  6.75603482]
0.3952294180175086
第3883组系数
[-8.01227412e-02 -1.50357995e-01 -2.81281964e-03  5.87836516e+00]
0.2740784154199783
第3884组系数
[-66.83333333 158.65384615  76.52564103 197.04192308]
5.635890045151431e+173
第3885组系数
[-0.08654963 -1.86736801  0.34852201  6.07603524]
4.032826618550344
第3886组系数
[ 0.34412857 -0.1

1.0950374787349286
第3978组系数
[ 0.19954904 -0.17925592  0.90661405  7.49449267]
0.42323298893450617
第3979组系数
[2.36024222 0.14403795 0.30612485 7.92535192]
0.4808345188307527
第3980组系数
[ 1.00265604 -0.69234174  0.63050083  8.09028446]
1.2022138694848472
第3981组系数
[ 0.09456158 -0.27659639  0.39534884  6.73893976]
0.30765654916165946
第3982组系数
[ 0.63220656 -0.92655191 -0.25255934  5.87241882]
0.47674573437751444
第3983组系数
[ 0.29686186  0.15780195 -0.25449226  6.41418936]
0.367080430709931
第3984组系数
[ 1.52892562 -0.26033058 -2.71132231  4.59253802]
755.802011375361
第3985组系数
[ 1.16714786 -1.37827194 -0.17083359  6.22735037]
1.006949354511582
第3986组系数
[ 0.05537459 -0.60260586  0.60108875  6.7406354 ]
0.4318014238174599
第3987组系数
[ 0.69712576 -0.5468184   0.19114969  6.64844395]
0.3482536711244959
第3988组系数
[0.95438448 0.31310883 0.42468649 7.48003757]
0.3504548435765487
第3989组系数
[-0.22489857 -1.07794342  0.93176853  6.5258917 ]
0.765770437324482
第3990组系数
[-6.45102189 10.22961901 -1.79245755  2.794429

0.3990456284435144
第4083组系数
[ 0.54925102  0.45743408 -0.6851401   5.66064251]
0.6071129627855573
第4084组系数
[-3.09477756e-03 -7.80189352e-01 -4.13417490e-01  5.30939672e+00]
0.516406048381643
第4085组系数
[ 0.27159604 -0.19888571 -0.01358595  6.69583774]
0.4264609741660194
第4086组系数
[ 0.68390499 -1.98644296  0.56994797  6.40594216]
4.277794089370419
第4087组系数
[ 0.70604485  0.57964144 -0.45840147  6.69386199]
0.6163092213570317
第4088组系数
[-0.09522379  0.3593467   0.1244085   6.46438413]
0.29524349521477544
第4089组系数
[ 3.08357921 -4.41429575 -0.24048121  6.24941553]
184691.6369368014
第4090组系数
[ 0.63188463 -0.51543296  0.37745584  6.83472117]
0.3619419169126607
第4091组系数
[ 0.93597672 -4.65696617 -2.39468898  1.41186977]
35990.15896227489
第4092组系数
[-0.32723577  0.15167683 -0.25513211  5.82334248]
0.4877572435349227
第4093组系数
[0.69696341 0.04157182 0.89455365 8.18740598]
0.5438830147311352
第4094组系数
[-1.1172579  -0.13779962  0.25086846  5.3334219 ]
0.7295721831781277
第4095组系数
[-0.22136859 -0.66839378  0

5.258729209814287e+23
第4189组系数
[-0.01280099 -0.04724225  0.30733554  6.59385867]
0.26344906046893374
第4190组系数
[ 0.17539142 -0.02355843  0.63558749  7.38965888]
0.4025045828086726
第4191组系数
[ 0.54307557 -0.349015   -1.31515618  5.30423699]
5.0874219763429815
第4192组系数
[ 876.54545455  873.90909091 1954.60606061 3483.89272727]
第4192组系数
[-130.51196809  -60.25531915   55.28989362    9.06650266]
8.31540102977671e+266
第4193组系数
[ 0.63433836  0.08687884 -0.01343457  7.13449462]
0.45360408066257124
第4194组系数
[17.80431352  2.07154129  5.15839032 20.37777328]
22.228110432624668
第4195组系数
[ 0.48567119 17.15535445  2.9984917  16.53443439]
30.896328077962853
第4196组系数
[ 0.70372348 -2.71199786 -1.12318164  4.07969305]
29.707656447064164
第4197组系数
[ 1.0057915   0.3735462  -0.05553312  7.03276643]
0.33603450935315976
第4198组系数
[0.9911915  0.7332372  0.96712747 8.45901132]
0.48097167025583054
第4199组系数
[-1.56628923  0.61323064  0.64036519  5.39907885]
1.0798612753075596
第4200组系数
[0.44980695 3.05598456 0.03714286

0.3570070496994797
第4293组系数
[0.46042956 0.93000261 0.03603093 7.49573995]
0.6228974403971668
第4294组系数
[-1.13770024 -2.41710562 -1.84071409  2.08357969]
106.27144480581754
第4295组系数
[-2.49982803 32.52424847  3.10222192 19.1396079 ]
2243.0915910510507
第4296组系数
[0.62157052 1.6883522  0.11328071 7.12801022]
0.48013700047727986
第4297组系数
[ 4.39233756  3.6111525   1.92066978 13.31029371]
2.9267801945941296
第4298组系数
[ 0.54330541  1.314211   -0.4345963   7.05084834]
0.9080893889604701
第4299组系数
[-0.36098021 -1.99717248  0.34213007  5.736541  ]
5.275061049864165
第4300组系数
[-0.14644351 -3.42887029  0.17948718  4.90460251]
823.4868489294755
第4301组系数
[-1.14925047 -1.25891428  1.53078155  6.28048319]
1.487691674309603
第4302组系数
[ 1.09487666 -0.31309298  0.44049248  7.48500022]
0.40491001191566417
第4303组系数
[ 0.09048733 -0.12244617  0.06962862  6.410143  ]
0.24350282914674576
第4304组系数
[ 4.49719034  0.97178384 -0.3439144   7.74657281]
0.6863909243818
第4305组系数
[ 1.31948969 -0.36065524 -0.03896721  6.9688056

178835473583332.9
第4398组系数
[-2.83096721  1.29439601  0.83819012  6.92895226]
307.13960862320886
第4399组系数
[ 0.23187251  0.34396208 -0.30076934  6.4225417 ]
0.4482234621057551
第4400组系数
[ 1.14971507  1.82905006 -0.32528512  8.08542608]
1.4030977979693364
第4401组系数
[ 1.49760379 -1.05980426  0.51831586  7.40085345]
0.7898895171288767
第4402组系数
[ 0.11864407 -0.83050847  1.05875706  7.14501695]
0.6293024275939731
第4403组系数
[3.21247498 1.67494997 0.34623082 8.94256004]
0.6460139622034368
第4404组系数
[-0.07553366  2.91365627 -0.188365    6.46649484]
0.5864546174212728
第4405组系数
[0.41240416 0.49936124 0.388405   7.34197868]
0.31652005654208953
第4406组系数
[ 0.71743384 -1.20883534  4.20080321  9.3137751 ]
1.2023023917676772
第4407组系数
[-0.58021719  0.8483464  -1.63970694  3.91837851]
17.32042571909644
第4408组系数
[ 0.55147059 -0.27113971  0.4046875   7.02692188]
0.3081582498827454
第4409组系数
[ 4.91027400e-01 -2.04234992e-03 -5.33470621e-02  6.52268025e+00]
0.24792516361887884
第4410组系数
[ 0.4994554   0.25321473 -0.

0.719376477638514
第4502组系数
[ 0.44381834 -1.96695197  0.26782614  6.57081569]
6.935960710541911
第4503组系数
[ 2.70823622 -2.25104681 -0.43753703  6.3225558 ]
10.402509478135245
第4504组系数
[-26.87213314 -61.62411204 -23.34645829 -72.79714837]
4.2279041508929444e+102
第4505组系数
[ 0.93041725  0.2957573  -0.13612565  6.75770639]
0.33483311241949204
第4506组系数
[-6.04920963 -1.49932481 -0.93887521 -2.39766781]
78531358.5337315
第4507组系数
[ 2.19483487 -2.70892474 -0.05971751  6.46963131]
74.34054657680126
第4508组系数
[ 0.0643897   1.64277716 -2.13881706  5.56269042]
316.39790811675255
第4509组系数
[ 1.49354733  0.85712414 -0.61735997  6.63743465]
0.6278738311506408
第4510组系数
[1.33064983e+00 5.49264659e-01 1.15109354e-03 7.29827701e+00]
0.3854565670987761
第4511组系数
[-2.39182923  9.60337384 -8.3079629   0.42314839]
2381902587011716.5
第4512组系数
[ 0.19841613 -0.55277178  0.22217423  6.45639453]
0.33328451024649697
第4513组系数
[ 0.44904519  0.01010264 -0.47271481  6.14877655]
0.4730326817402197
第4514组系数
[3.29291598 0.5040

68948702891779.08
第4605组系数
[-5.1006184  -1.8596271   2.62509881  6.73484493]
7193383.19743851
第4606组系数
[0.27830832 2.99386085 0.13042192 8.05329623]
0.8952145025253375
第4607组系数
[ 1.39419941  0.01287082 -0.07438218  7.12355151]
0.3676123206135576
第4608组系数
[ 1.28740203 -2.24015879 -0.21714198  6.29409358]
13.803767398761861
第4609组系数
[ 0.10308259 -1.          0.16945986  6.01619594]
0.5281951201889193
第4610组系数
[-56.05928339 -68.20912052  65.41889251   6.99327687]
9.093074688320288e+134
第4611组系数
[-0.41919676  3.46860312  0.54545252  7.50897155]
0.669066610649593
第4612组系数
[-1.77742131 -1.87623894 -4.11465692 -2.03384711]
838491.5855485781
第4613组系数
[-0.0538277  -0.24067975  0.02228156  5.98453788]
0.2527251751690323
第4614组系数
[ 0.74809825 -1.80008971 -0.40366285  5.68574384]
2.7412072036659896
第4615组系数
[0.62960824 0.91427207 0.42777495 7.94408464]
0.49527558085377493
第4616组系数
[ 0.21369375 -0.41581845 -0.43429835  5.85884796]
0.5176226305397225
第4617组系数
[-0.30463901  0.08266447  0.05873276  6.

28391342.841154244
第4710组系数
[-0.98562708 -0.30884698 -1.6117413   3.66835793]
39.913116078410475
第4711组系数
[ 4.25420841e-01 -2.17409528e-01  1.69017924e-03  6.23004147e+00]
0.29421876603098296
第4712组系数
[-19.41298246   0.78947368  -0.83052632  -1.9471193 ]
3.072417459107993e+36
第4713组系数
[-0.90271349 -6.38472162  0.28129715  4.49646301]
839172264.397889
第4714组系数
[ 2.92571773 -1.79261193 -0.27954226  7.11884802]
3.725907446551024
第4715组系数
[ 0.19091196 -0.49826717 -0.29645701  5.82032809]
0.3674525937206301
第4716组系数
[-0.55152416  1.02575465 -1.54173383  4.4664364 ]
16.92128183587194
第4717组系数
[ 0.25609218 -0.13757447  0.06262049  6.74449672]
0.3510602241335144
第4718组系数
[ 6.84745763 16.83050847 17.53728814 39.98422034]
53680899.32069749
第4719组系数
[1.1173542  1.42658448 1.06190401 8.7744808 ]
0.5486231521025824
第4720组系数
[1.86102205e+00 6.27819459e-02 2.86421246e-04 7.31895305e+00]
0.40613288874647857
第4721组系数
[ 0.63774836 -0.8540587  -0.17970094  6.45475099]
0.7050771272652382
第4722组系数
[-0.3793

9.528789945553136e+33
第4815组系数
[-0.0176172  -2.45117946 -2.51141833  2.80853156]
791.9472962194689
第4816组系数
[ 0.98321648 -1.88407923 -0.2384487   5.89678315]
3.166983936774504
第4817组系数
[ 7.88971223 16.83606557  3.21925595 26.82089022]
22592.728261043398
第4818组系数
[ 1.81015817e-01  1.74114421e-02 -2.44430534e-03  6.41770582e+00]
0.22905296290057228
第4819组系数
[ 1.16694525  0.5200324  -0.46888091  6.61413411]
0.4934864027407881
第4820组系数
[ 0.63428696 -0.05776134 -1.94068857  4.55662053]
36.28889070563026
第4821组系数
[ 3.02189392 -3.25341745 -1.37799012  5.59024802]
802.6519161533058
第4822组系数
[ 8.84186314 -1.89792984 -4.41629015  3.71208207]
54419.58838779308
第4823组系数
[0.54183582 0.02784043 0.39757003 7.37516581]
0.3332271063462387
第4824组系数
[-1.56219594 -1.46711961  0.08995974  5.64680003]
9.810390023597991
第4825组系数
[ 0.1301298   0.12729448 -1.20179571  4.81992351]
2.5657413904321245
第4826组系数
[0.23648437 0.5164965  0.03881992 7.09799203]
0.4805440124194652
第4827组系数
[ 0.7864978  -0.344058    0.31

0.44115417200304136
第4920组系数
[1.12285538 5.34715077 0.72804923 9.37383705]
0.832568254006697
第4921组系数
[0.45109402 0.55441218 0.39429377 7.53406031]
0.36443795968267095
第4922组系数
[-0.97737695 -0.88627331  1.16496484  6.50318924]
1.1935250943249898
第4923组系数
[ 0.09255144  0.36915207 -0.21106811  6.0801228 ]
0.333634515724227
第4924组系数
[ 0.17891566 -0.6686747   0.24879518  6.28481928]
0.362107316786748
第4925组系数
[ 0.83546856  1.57900356  2.16253855 10.02228636]
0.8175597441375633
第4926组系数
[2.39268004 0.40996869 0.46462468 8.45798652]
0.5491850685886981
第4927组系数
[ 0.14591144 -0.02534248 -0.33551333  5.88381089]
0.3339177337810182
第4928组系数
[ 0.84958183 -1.92284506 -0.4966357   5.66073858]
4.035971941250482
第4929组系数
[1.16111762 0.14472143 0.58345324 7.78281429]
0.3837843872962007
第4930组系数
[ 7.83404225e-02 -2.33135092e-01 -4.52617870e-03  6.06695303e+00]
0.23909343602084202
第4931组系数
[ 0.41835694 -0.93095373 -0.99321246  5.10435388]
1.7468185941829564
第4932组系数
[ 0.38716565 -0.09578098 -0.69474387 

0.3119569289225052
第5024组系数
[ 1.11588574 -0.62790698 -0.47611321  6.03562073]
0.47229066994698676
第5025组系数
[-9.65845465 -3.73012318 -2.85890258 -2.82770437]
1.1938439024559176e+20
第5026组系数
[ 0.53313796  0.05739405 -0.30477908  6.66016501]
0.5291485650670177
第5027组系数
[ 0.03282276 -0.20131291 -0.46484318  5.68552079]
0.49205844318183384
第5028组系数
[-0.25901268  0.07732488 -0.21155466  6.01242106]
0.505547972864794
第5029组系数
[ 0.51664462  0.24211806 -0.24061646  6.5600525 ]
0.3399370334521227
第5030组系数
[-0.16642121  1.01099656  0.26116838  6.80641041]
0.40056338131634467
第5031组系数
[0.71301005 0.3077469  0.37713385 7.52892667]
0.33526049936291474
第5032组系数
[ -0.29103997 -13.52561731   2.84336041   1.88494531]
2.066512106617453e+22
第5033组系数
[ 0.28827399 -0.05867963 -0.35779695  6.07321994]
0.3615747628923622
第5034组系数
[-0.07283073  0.2628734  -0.32972973  6.12278236]
0.5361796733473598
第5035组系数
[ 0.94716528  3.13131486 -2.15141379  5.93426109]
134.65172239952392
第5036组系数
[ 0.16427048  0.34404186 -

35.986776684485
第5128组系数
[-0.08165826 -0.50401033  1.0375938   7.45699803]
0.6960587091456869
第5129组系数
[ 1.32017369 -2.44483584 -0.42598254  5.35005516]
14.241370214710775
第5130组系数
[ 9.69303652 -3.98255705 -3.24212204  7.6490163 ]
296105.915951371
第5131组系数
[ 0.51700368 -0.08318015 -0.04192058  6.89839778]
0.41203982432210784
第5132组系数
[-0.15185113  1.0394238   0.774504    8.10081715]
0.8732789884299997
第5133组系数
[ -39.82330827 -122.27944862   46.02130326   -4.11365915]
3.977091730055223e+245
第5134组系数
[ 1.12518995 -0.167437    1.17311954  8.32508247]
0.527344223899805
第5135组系数
[-0.91343183  1.4185057   0.29067117  7.0505263 ]
1.4077819671433311
第5136组系数
[ 3.11512878 -0.72312514 -0.31803838  7.48405103]
0.867462233138937
第5137组系数
[ 0.05368171 -0.68028504  0.53892167  6.8278039 ]
0.5474630116321018
第5138组系数
[ 2.16783217  0.09090909 -9.24589364 -6.51300211]
944968670572.0808
第5139组系数
[ 3.00432633  1.19839308  4.28077874 14.39222559]
5.218147969951057
第5140组系数
[ 1.0331384   0.5176831  -1.2543

7.552333704703566e+40
第5230组系数
[ 0.62121805 -5.41556391  0.74135338  5.29449714]
8131262.754253731
第5231组系数
[ 3.543347    0.10875885 -0.82146851  7.46912262]
1.1411445256701045
第5232组系数
[ 3.31720673  0.34721972 -0.20815141  8.13609948]
0.726936338660834
第5233组系数
[ 0.38488667 -1.58801344 -0.33942407  5.51750081]
1.5577510587459726
第5234组系数
[ 1.78625954 -1.79389313 -2.0480916   4.78319847]
53.03802022696171
第5235组系数
[ 2.54608113 -1.59997206 -0.33589158  6.3614474 ]
1.366400032828563
第5236组系数
[ 1.15161453 -1.10924774  0.08658971  6.57501339]
0.6642975563381652
第5237组系数
[0.18201732 0.84637638 0.14648856 7.12494083]
0.38998647365509354
第5238组系数
[ 0.8049769   0.15690461 -0.0513876   6.87898926]
0.2925261169728586
第5239组系数
[ 0.74138492 -1.86529223  0.68566681  6.50436073]
2.8352251344947104
第5240组系数
[-0.58495539 -3.40597121  1.46913017  6.94478153]
2811.8595641921497
第5241组系数
[0.5874287  1.38831604 1.74022601 9.67665157]
0.9026262289893051
第5242组系数
[-0.02261862  0.25614178  0.10732038  6.2228

0.3785112838155486
第5335组系数
[-2.5        -3.         -1.75342466  1.13349315]
6164.7736622935
第5336组系数
[ 0.78875788 -0.45775158  0.11315023  7.05352084]
0.4652814255008734
第5337组系数
[-0.66333225 -0.44456526 -0.18226958  5.19596934]
0.5865771636839842
第5338组系数
[ 3.27070682e-01  4.80444499e-01 -2.83924957e-03  6.77849547e+00]
0.29462617689268694
第5339组系数
[ 0.21142718 -0.04874072 -0.15683473  6.26683022]
0.27207664613871324
第5340组系数
[-0.91350702 -1.65055828 -0.67579625  4.00992002]
2.883958909262892
第5341组系数
[1.03424684 0.54556689 1.64877348 9.73187344]
1.0583583034170188
第5342组系数
[-0.45454545  0.34421134  1.49473266  7.98597496]
0.7402768270444148
第5343组系数
[ 0.93098038  3.08177505 -0.85735345  6.67368438]
1.2003658071666805
第5344组系数
[-7.32258065 15.80645161 21.53863466 45.53082521]
1.4545330962405699e+18
第5345组系数
[ 1.40450659 -0.56721272 -0.21455654  6.33785491]
0.4325692256910599
第5346组系数
[0.07651824 2.23197882 1.48363741 8.79549726]
0.6723688730455866
第5347组系数
[ 53.02188552 -33.9349046 

0.44744746333292307
第5440组系数
[-1.06963169  0.21058974 -0.39790615  4.75523575]
1.0192905518276851
第5441组系数
[ 0.62872436  0.04597299 -0.07380139  6.90355692]
0.34777802903410904
第5442组系数
[-0.08032295 -0.19541518 -0.04772996  5.70025831]
0.3145314851332704
第5443组系数
[-1.31720978 -2.19653768  0.95264766  5.35373727]
9.014533901709957
第5444组系数
[ 1.16543575  2.35302806  3.4614771  12.81671699]
3.040979143572346
第5445组系数
[0.02844086 0.36517939 0.36986301 6.85144014]
0.297192088159721
第5446组系数
[-0.1439896  -0.12387299  0.21988204  6.15609511]
0.28298993053709903
第5447组系数
[-0.40689655 -0.35517241 -1.28017241  5.21457759]
14.07556014237305
第5448组系数
[-0.89752523 -0.18336537 -1.39856639  3.99483061]
15.77540651491567
第5449组系数
[ 2.24769141 -1.04436662 -1.40845273  5.88832055]
4.586729734037419
第5450组系数
[0.10293435 0.46012207 0.07853378 6.59956005]
0.2833728977609499
第5451组系数
[ 1.27272727  1.32864074 -1.39926827  6.30695777]
6.322131078825754
第5452组系数
[-0.19564095 -2.38330642 -0.13547843  4.14740725

1.6524309251780693
第5542组系数
[-1.42110184 -3.447534   -0.05188164  4.94922263]
2089.4890501654636
第5543组系数
[-1.1955609  -0.67374709  1.72482308  8.21769173]
5.035907543103222
第5544组系数
[ 1.4992722  -0.40611354  4.99262494 14.47116739]
19.230409098415773
第5545组系数
[ 1.96094845 -2.54775258 -0.55892784  6.1399967 ]
41.946494581826975
第5546组系数
[ 1.6452989  -2.13354616 -0.94002147  5.39820064]
6.87931657008984
第5547组系数
[ 0.17820176 -0.12642315  0.07125718  6.45029198]
0.22950120580031758
第5548组系数
[4.59405941 0.75247525 0.40694504 9.66681877]
0.9234099114759516
第5549组系数
[ 0.39997641 -1.0021235  -0.35489416  5.87753876]
0.748710255181559
第5550组系数
[0.46784389 0.89258801 0.10502756 7.49186031]
0.5238292141532722
第5551组系数
[ 0.1865503  -0.14136159 -0.07828     6.24084014]
0.23998395251699292
第5552组系数
[ 0.78696207  2.26360082 -0.47046917  7.42043811]
1.0649904417008813
第5553组系数
[  0.48171025 -29.08527209  -3.86458375 -14.41358137]
6.164519442578076e+50
第5554组系数
[-3.11951303 -1.32814575 -2.34891878  0

2.0045014243311558e+159
第5644组系数
[ 0.90804174 -0.25577043 -0.04620522  6.45355047]
0.3429214073043459
第5645组系数
[-0.59392549  0.22757376  0.17906721  6.06288808]
0.45520342744529824
第5646组系数
[-6.35232473 -3.16035146  1.24061871  4.33023156]
2471350422.657646
第5647组系数
[1.13442822 0.64010543 0.15977291 7.47936131]
0.37584280846192214
第5648组系数
[-0.22882727  1.99120834  0.09023658  6.4328755 ]
0.5106671180850731
第5649组系数
[ 0.3445607  -0.09817973 -0.10174526  6.54987448]
0.31349110268269015
第5650组系数
[ 1.07459499  1.53620488 -0.24437442  8.01316462]
1.225485171220811
第5651组系数
[-1.72727273 11.97202797  5.0018201  17.36045119]
228.2534677835912
第5652组系数
[-2.04048664  3.37913841 -2.24132429  4.65088552]
21737.69571517238
第5653组系数
[ 1.91433843 -5.47124407  0.13759884  6.44618305]
37953755.24294649
第5654组系数
[-0.01905761  1.85071541  0.78447824  7.82613199]
0.5324595999340795
第5655组系数
[ 1.85762427 -1.93410089  1.597813    7.88525794]
4.277850376899519
第5656组系数
[ 0.29230958 -0.22607345 -0.03883836  

1.596960263326894
第5749组系数
[0.04541047 0.22199035 0.29833905 6.8308996 ]
0.2800248795215794
第5750组系数
[ 0.48826929 -0.59206759 -0.54356821  5.7754598 ]
0.5707431866214533
第5751组系数
[ 1.171875   -3.421875   -0.06197917  5.60389062]
1159.0146221390048
第5752组系数
[-0.45625886  1.67725461 -0.87506031  5.18169724]
1.491155836588327
第5753组系数
[-0.22036087 -0.13840927  0.17441248  6.06641865]
0.2874201108135995
第5754组系数
[ 0.42566783 -0.46051103 -0.40473212  6.17549942]
0.6103655318283702
第5755组系数
[ 1.48598119 -2.01009072  0.85144516  7.92976524]
11.529218544042681
第5756组系数
[ 0.25029559 -0.56885806  0.03662047  6.12368665]
0.3021640678565822
第5757组系数
[ -0.12401942   6.02428091 -14.24593516  -3.65431728]
2.899726084061385e+24
第5758组系数
[-1.33422725 -1.72039772 -1.15913029  2.13351762]
5.544523717923161
第5759组系数
[  6.23009842 -20.39721144  -7.81511114  -4.83513407]
8.882911311407776e+36
第5760组系数
[-0.81606487  0.75129862  0.84335487  7.16327987]
0.8129112896641336
第5761组系数
[ 0.38225889  0.03333333 -0.0

0.6486077887673498
第5852组系数
[ 0.97759952 -0.06650144 -0.31361056  6.53218246]
0.35912782758181194
第5853组系数
[-0.59056317 -6.36707255 -0.30266362  2.99432344]
229573397.06320617
第5854组系数
[-2.6533538  10.72676327 -8.05417906 -2.15660896]
107940464348176.14
第5855组系数
[ 0.11485225  0.15981505 -0.08672456  6.55771481]
0.37233850909520405
第5856组系数
[ 0.59969384 -0.23306544 -0.12361271  6.59195178]
0.3130495237473452
第5857组系数
[ 2.00367868 -0.76967247 -2.10072685  4.72917154]
33.63421157867091
第5858组系数
[-0.54679144 -1.95454545 -2.68930481  1.90384759]
1193.2842067451595
第5859组系数
[-0.85167575  1.06053402 -0.60978928  5.36207149]
1.588263916809869
第5860组系数
[ 0.42754534 -0.21751565 -0.33809287  6.23011559]
0.4001375013692943
第5861组系数
[0.23093116 3.19115529 0.26526219 7.39665838]
0.5822591023286671
第5862组系数
[ 0.20006793 11.30400815  7.28848505 19.41699083]
73.9552403644094
第5863组系数
[ 0.52936331 -0.56165061  0.3909645   7.05631818]
0.4377913665799341
第5864组系数
[ 108.5        -328.          -46.47674419

0.5533061852119113
第5956组系数
[-0.3185439  -0.18747017 -0.14099358  5.41033223]
0.3606889603293079
第5957组系数
[ 0.01400056 -0.10977623  1.20430353  8.03964066]
0.7400837626949537
第5958组系数
[ 1.03907923 -1.74179158  1.26389186  8.01863035]
4.576603559870625
第5959组系数
[ 1.63461122 -0.21709115  0.33175384  7.92077784]
0.5942400473045107
第5960组系数
[-5.65822416  1.70305677 -7.80829694 -6.7233115 ]
2.981780698097607e+19
第5961组系数
[ 0.46227054 -0.93191594  0.55562894  7.1085114 ]
0.753140070961659
第5962组系数
[ 0.2083987   0.12430979 -0.01470588  6.78266188]
0.39951003468479296
第5963组系数
[-35.8853641  158.57534247  -1.37635184  18.53982696]
1.7292701444249025e+62
第5964组系数
[0.22729913 1.49136009 0.03521127 6.65964875]
0.45268280812976014
第5965组系数
[ 0.01004998 -0.28945027  0.07675845  6.26833301]
0.2767258208518757
第5966组系数
[ 0.69280268 -0.58803916  0.12357976  6.75567375]
0.3847384976473992
第5967组系数
[ 0.68535314 -4.63125103  0.07291309  5.66582617]
411588.2744491133
第5968组系数
[ 1.93384714 -0.2507386  -0.38

1.3765761469587066
第6061组系数
[ 0.90725806  4.89112903  5.81834677 14.97157863]
3.722962921579655
第6062组系数
[-4.95382131 -1.23268299 -3.55855266 -2.75025665]
92227575874.91014
第6063组系数
[-1.40279705  0.06027697  0.13674768  5.37699618]
1.443391769863026
第6064组系数
[-0.30603822 -2.911517    1.10677095  6.68218802]
260.79061922434494
第6065组系数
[ 0.83745252 -0.33935178 -0.03954233  6.72386322]
0.31862674915933764
第6066组系数
[ 1.45416667 -1.49583333 -1.5696934   4.10784237]
3.604613580513566
第6067组系数
[ 0.68440799  3.66673938  2.00776547 10.74518934]
1.2307631657289029
第6068组系数
[1.84400082e-01 6.17410990e-03 7.12080675e-02 6.48041984e+00]
0.2230687090200857
第6069组系数
[1.80942003 1.11518747 0.0832627  7.84108891]
0.49232336308706537
第6070组系数
[ 1.25970849 -0.16563041 -0.17971664  6.96784079]
0.4220915860697951
第6071组系数
[ 0.54482984 -0.20576478 -0.08532564  6.70135465]
0.34660451215390004
第6072组系数
[-0.2302343  -3.10889338 -0.46564209  3.38370394]
70.7345605068035
第6073组系数
[ 0.80313873  1.3212806  -0.789

0.49800101526326185
第6165组系数
[0.72485464 0.1280088  0.07438806 7.25546356]
0.3945044196173575
第6166组系数
[ 7.74122367 -5.08124373 -3.03109328  2.78072217]
514320.5388913297
第6167组系数
[0.3954743  0.24351873 0.69836116 7.66350396]
0.36525264946134095
第6168组系数
[ 0.66437638  0.24598683 -0.2852498   6.34531732]
0.34802420463119393
第6169组系数
[-0.79547607  0.70983083  0.37171333  6.14642939]
0.5551359669650794
第6170组系数
[ 0.49958781 -0.70591051 -1.22035305  4.48676297]
1.8499150113393783
第6171组系数
[ 0.96030707 -0.14490099 -0.83314432  5.83517491]
0.8177127936094909
第6172组系数
[ 0.64034261  1.30731314 -0.03502446  7.19123102]
0.4352469537735046
第6173组系数
[23.59770578 -3.68917287 -6.09961763  7.80915375]
1424398544.8081572
第6174组系数
[-0.83107738  1.27388145  0.33567113  7.2794385 ]
1.577634921042517
第6175组系数
[ 3.52761341  1.35552268 -0.31065089  8.04076923]
0.6633211326648064
第6176组系数
[ 0.38921838 -0.20796195 -0.12261555  6.39323697]
0.2745108449977422
第6177组系数
[  3.29094682 -24.22033722  -0.91394725   0

0.6079656907977573
第6270组系数
[0.52941893 0.47691122 0.33257588 6.98336999]
0.3753665021690447
第6271组系数
[ 0.75490432 -0.29520198 -0.90934397  5.58798917]
1.0337194846555022
第6272组系数
[-2.9675812  -0.11191252  3.32320374  6.51777682]
44.68327888415722
第6273组系数
[22.6484375  -4.875       1.71984145 20.87174575]
185745749392.9721
第6274组系数
[-0.01566564  0.13938556 -0.05227503  6.11193293]
0.27204935867450686
第6275组系数
[-12.64124668  -8.62599469 -20.68740053 -33.80623475]
5.135512217742159e+52
第6276组系数
[0.36972823 0.04478076 0.1416485  6.54665032]
0.2788429837590583
第6277组系数
[ 1.40787849  1.84656705 -3.1242282   4.29401704]
2879.6430613345497
第6278组系数
[-1.62029117  1.50708867 -0.05693083  6.08233017]
4.218970795043281
第6279组系数
[ 0.33137479 -0.6565283  -0.3334831   5.88094967]
0.4517328256977783
第6280组系数
[ 1.62966043 -0.32421131 -0.02970551  7.07402276]
0.40635079407323577
第6281组系数
[-0.77502505 -4.91782421  3.25399906  8.38286461]
4760746.363208673
第6282组系数
[ 0.59222359 -8.89701108 -0.5354864   4

1.5624248642235068
第6375组系数
[ 0.3016557   0.2827873  -0.01983569  6.50638171]
0.2673071683767508
第6376组系数
[-2.13746284  1.88591629 -3.36571061  0.24430626]
196803.28843553478
第6377组系数
[ 1.35112713 -3.3607135  -0.16532712  6.2517605 ]
1689.6544270054953
第6378组系数
[-0.4982699   5.88581315 -0.46387543  8.91232457]
8.967555587362305
第6379组系数
[ 0.7208369  -3.09053227  2.67567603  8.63069031]
912.7305297700768
第6380组系数
[19.44237288  0.675       9.54220339 27.39521695]
5093.826729589918
第6381组系数
[ 0.38416448 -2.06130815 -0.30534693  5.65450564]
6.659556616823798
第6382组系数
[ 0.91746196  0.70135453 -0.31233928  6.91888816]
0.474147753937485
第6383组系数
[ 0.34459459 -0.18243243 -1.36283784  4.84419595]
4.566804651178976
第6384组系数
[ 0.05789111 -2.49023662 -0.08079485  5.15455341]
19.123624528784173
第6385组系数
[-1.53448276  5.41483804 -3.58641588  4.5590815 ]
1287264.251643382
第6386组系数
[ 0.49305556 -0.11878655  1.05080409  7.88730994]
0.45071184324896413
第6387组系数
[ 0.14027746 -0.07357277  0.061324    6.47

0.31003576166714003
第6479组系数
[-1.93975401 10.11444653  0.5076387   8.68860985]
6.161990850618206
第6480组系数
[ 1.14585918e-01 -6.19208406e-03  1.56204490e-01  6.62777678e+00]
0.2508717626167229
第6481组系数
[0.38959975 0.11867868 0.23307321 7.05506543]
0.2759305829458201
第6482组系数
[ 0.42517906 -2.59132627 -0.2007992   5.58467114]
40.688679862183626
第6483组系数
[-0.12438792  0.2336477  -0.68946143  5.64555856]
1.069005165377661
第6484组系数
[  4.88717572 -33.8042095    1.1071953    1.45230299]
2.726336975340464e+66
第6485组系数
[ -58.5        -193.         -112.63013699 -302.41726027]
第6485组系数
[ 0.34595765 -0.06884656 -0.26597918  6.44806488]
0.44659380933513526
第6486组系数
[-0.04034312 -0.68215713  0.35151658  5.7706228 ]
0.48281179042855726
第6487组系数
[ 0.0292562  -0.04842975  0.38528926  6.85985455]
0.31368289577045283
第6488组系数
[-0.01274004  0.15641485 -0.03071852  6.49543303]
0.36753146252800384
第6489组系数
[-1.77051156e-03  8.87101635e-01 -2.30731560e-01  6.98220184e+00]
1.0620819492294802
第6490组系数
[ 0.01971

12.78910245020864
第6583组系数
[-0.4143397  -0.49222653 -1.13431149  4.28034472]
2.9999870962640407
第6584组系数
[ 0.74539227 -0.81019614  0.47124483  6.94796028]
0.5014919018991774
第6585组系数
[ 1.16242938 -0.13906009 -1.25        5.78813046]
3.2322052137478683
第6586组系数
[ 0.29422192 -0.07395053  0.02136586  6.36455419]
0.23641388299131647
第6587组系数
[ 1.11609612 -0.71389445 -0.2753356   6.52032241]
0.5415456458725991
第6588组系数
[ 1.29322152 -0.64897342  0.29647267  7.34310915]
0.5372822453532955
第6589组系数
[ 0.37545389  0.50326797 -0.28355958  6.808061  ]
0.6182605902889143
第6590组系数
[-0.65034695 -6.33616037 -1.71385891  1.29823921]
96920655.75783446
第6591组系数
[ 0.22061891 -0.52554048 -0.56196202  5.38090693]
0.5011437513780502
第6592组系数
[ 1.05309735 -2.37758112  3.20827331 11.25244495]
317.4239420088368
第6593组系数
[ 0.14132906  0.31251579 -0.39319842  6.02173961]
0.42447528755466674
第6594组系数
[-0.39731672  3.31234617  1.0393372   7.65429698]
0.6829925284604743
第6595组系数
[-4.48828829 -0.21333333  0.89506306 

1.3027776729648595
第6687组系数
[ 1.40633534 -1.27112429 -0.76492159  5.46801436]
0.9298844135446934
第6688组系数
[-0.07208426  1.11978187 -0.17368652  6.22860065]
0.4339854287621262
第6689组系数
[-0.27000047 -0.40341581 -0.7721531   4.81382221]
0.9722022316554345
第6690组系数
[ 0.581203   -0.77009199  0.79804183  7.41137955]
0.6120459367451878
第6691组系数
[ 0.77402669 -2.26539793  0.63665959  7.79339405]
43.858083709929915
第6692组系数
[-0.00948985 -0.49880707  0.1867839   6.15424717]
0.3074408088486788
第6693组系数
[ 1.02967626 -0.04406475  0.66564748  7.86406835]
0.41543873256154307
第6694组系数
[-7.74919169 -3.64249423 19.18752887 13.42530716]
564878163.2852857
第6695组系数
[ 0.15504298  1.62480324 -0.56480809  5.87083424]
0.6417764429073255
第6696组系数
[0.07927675 0.57579786 1.0924218  8.17629618]
0.581557980865558
第6697组系数
[ 1.32986548  0.17524262 -0.14629228  7.02666649]
0.36599928954438554
第6698组系数
[ 2.01373431 -1.21134265  0.09905281  7.21364457]
1.020449504868597
第6699组系数
[ 1.46523047  0.06476712 -1.47519784  6.0

0.8439692945053596
第6792组系数
[ 2.93338835  8.89672247  2.87281302 13.80833223]
1.7229977870057012
第6793组系数
[-0.21486088  0.18142929  0.40244925  6.87349174]
0.4190759830456169
第6794组系数
[0.12656495 0.05305445 0.51480595 6.64792091]
0.37859802815609256
第6795组系数
[-0.74273859  0.19917012  0.0744537   5.52803616]
0.49226043655307994
第6796组系数
[ 0.22188497  0.1569941  -0.33584118  6.22577115]
0.40598664232882903
第6797组系数
[-0.38321512  1.31082923 -0.55937539  5.78424186]
0.9259323283283939
第6798组系数
[ 0.18281833 -0.11214795 -0.15595309  6.18057776]
0.26486348219678035
第6799组系数
[ 6.68711208 -7.3705732   1.34282585  9.07428258]
1708553319858.7078
第6800组系数
[0.75840437 1.90914427 0.12754103 7.88235144]
0.5997378152566721
第6801组系数
[0.90767713 1.19641633 0.58659552 8.57784436]
0.7147084421859984
第6802组系数
[ 0.05672106 -0.4005439   0.45251748  6.5715488 ]
0.3258449636210596
第6803组系数
[0.33098775 0.02289147 0.14431676 6.99264285]
0.34172569029562594
第6804组系数
[ 0.77715431 -0.02997996  0.12752978  7.2772379

98578878499.81021
第6898组系数
[ 0.14469727 -0.53646625 -0.74145984  4.70043222]
0.6304560849850469
第6899组系数
[ 0.41411661  1.36006176 -0.94009264  6.89840894]
4.190546772382089
第6900组系数
[ 0.82822687  0.00741994 -1.14199101  5.73608932]
2.495570063541408
第6901组系数
[ 0.05370069 -0.30866206  0.27751118  6.48408438]
0.27975592585382164
第6902组系数
[ 1.63032906 -1.78359542 -1.13312923  5.0829687 ]
2.870324379005821
第6903组系数
[-0.87613121  0.41934395  1.38299757  8.14674971]
1.7774089031380742
第6904组系数
[ 3.11111111  1.59803546 -0.15945911  7.99192882]
0.6207894684117731
第6905组系数
[-0.44542991  0.09101425  0.32411733  5.86935236]
0.4339285165944596
第6906组系数
[0.40105704 0.26717551 0.34530318 7.50321197]
0.4525553130508415
第6907组系数
[ -34.26470588  -63.02058824  -82.41764706 -170.20376471]
9.318704705011994e+184
第6908组系数
[  1.03439325 -13.94393251  -0.05788449   4.59668138]
1.352328590912213e+25
第6909组系数
[ 1.13363029  1.53452116  3.77505568 12.54964365]
2.516776130200297
第6910组系数
[  0.24320668 -10.4281985

0.3591018721694685
第7001组系数
[-5.27422817 11.65956744  4.56215948 12.61314017]
12795057.941076372
第7002组系数
[-0.03483698 -1.17972962 -0.4571311   4.65475411]
0.6379988719690262
第7003组系数
[17.00160359 36.62780629  8.63293778 40.46614496]
12596962.811865907
第7004组系数
[ 0.76467487 -0.88552485 -0.82701014  5.49353762]
1.0419561473884449
第7005组系数
[-0.1        -0.20793651  0.86481481  7.07264286]
0.4140488549571506
第7006组系数
[-0.42483791  1.84691604  0.20184539  7.44508446]
1.0549715841548084
第7007组系数
[ 2.28741093  3.          9.31876485 21.59528266]
407.4184376211267
第7008组系数
[ 2.86929967  0.07810598 -0.2783093   7.50156702]
0.5657278840079732
第7009组系数
[ 0.4987899   1.8332352  -2.07367762  3.95803221]
26.719812297304962
第7010组系数
[ 0.21299891 -0.83611187  0.27750475  6.59049301]
0.5768596322825102
第7011组系数
[ 2.11452107e+00 -5.33497899e-02 -5.39461094e-03  7.12158233e+00]
0.46732325473239456
第7012组系数
[-0.25677185 -0.72285843  0.28009201  5.9513322 ]
0.4438206072456783
第7013组系数
[-8.44594595e-03 -8.

0.29229999675389695
第7106组系数
[1.10223456 0.11113314 0.47707743 7.66286004]
0.36274028266663894
第7107组系数
[-0.38474204 -0.77442371  0.97800851  6.51021398]
0.6005679022221525
第7108组系数
[-0.81276649 -2.05882353 -1.45112558  2.93965866]
16.629482730851326
第7109组系数
[ 1.05296443 -2.02740888 -0.44280239  5.54780711]
4.220578127729209
第7110组系数
[-0.52516941  0.09906421 -0.88299451  4.75720136]
1.665986873760847
第7111组系数
[ 4.3254818   1.39721627 10.02198979 21.27598501]
189.53944426298239
第7112组系数
[ 1.99619082 -0.16778523 -0.0738255   7.25684382]
0.4412334867697635
第7113组系数
[ 0.94819884  0.10236015 -1.7988755   5.54950814]
34.33108230018827
第7114组系数
[ 1.38211382 -2.38888889 -1.91799458  3.80584607]
30.944200846189332
第7115组系数
[ 1.50374301 -0.0651513  -0.19334576  6.7855626 ]
0.380536104739366
第7116组系数
[ 1.42804598 -0.31034483 -0.75517556  6.31085379]
0.8439959068039633
第7117组系数
[ 0.62515736 -0.23914738 -0.37406332  6.31980902]
0.42969096699332876
第7118组系数
[-8.10479793 15.55989233 11.33109017 15.3

1.3763852821853482
第7211组系数
[ 1.13668518 -3.1814187  -0.4973384   5.58960806]
517.542903632291
第7211组系数
[ 0.22375639  0.68112804 -1.65718993  5.23211452]
23.385283152138353
第7212组系数
[-0.76408421  1.79361717  1.36493309  8.71929368]
1.6394279770130311
第7213组系数
[ 1.21208617 -0.10490457  1.5564617   8.76557462]
0.6071217121573169
第7214组系数
[1.24331874 2.49144015 0.81656756 8.94302927]
0.6358371537047021
第7215组系数
[  3.06019391 -12.0399123   -1.14190277   4.57949364]
1.628233404745295e+21
第7216组系数
[ 0.23375179 -0.77827899 -1.39120246  4.83549637]
7.570279349523628
第7217组系数
[ 1.44559324 -0.32109554 -0.02710917  6.96734006]
0.37770844189548197
第7218组系数
[ 0.17411627 -0.42740286 -0.29996118  5.71074568]
0.3289459616458741
第7219组系数
[ 0.8529468  -0.86084672 -0.13714237  6.04810073]
0.4490328010663794
第7220组系数
[0.35898214 0.14285714 1.25590656 8.53996246]
0.7574515861915084
第7221组系数
[0.37519623 3.95267997 0.02825746 7.14709352]
0.6342708350024994
第7222组系数
[1.8899606  0.23855454 0.09360141 7.4056826

0.8980016373346462
第7315组系数
[ 0.2889348  -0.96979509 -0.50032381  5.46532705]
0.6845829873773824
第7316组系数
[-0.18921775 -0.44465308 -0.25879722  5.31922907]
0.37131796686179125
第7317组系数
[ 2.98019802  5.         -0.62634524  9.99412398]
3.9678415244228833
第7318组系数
[2.24710696 1.40656927 0.91602028 9.45446005]
0.7123755994939179
第7319组系数
[ 0.45498051 -0.62868603  0.08956042  6.3445629 ]
0.33755318624522757
第7320组系数
[ 3.40831431 -1.0265177   0.23168046  7.98233088]
0.9618022842734357
第7321组系数
[0.1375223  0.41619934 0.11043844 6.41171361]
0.3305899951640232
第7322组系数
[ 1.46515113 -1.48135924 -0.15521476  6.36350357]
1.2403981405989286
第7323组系数
[-0.02260574  0.02916869  0.11351483  6.31717307]
0.23991690030373578
第7324组系数
[-1.46578234  4.3343993   0.20571531  7.128114  ]
2.3211064762760034
第7325组系数
[ 11.59787585 -35.45426662  -3.36898004   3.18309971]
5.526126542897537e+71
第7326组系数
[ 1.01226087  0.81275992 -0.32677566  6.74747226]
0.45305677407294637
第7327组系数
[ 0.03333333 -2.39122807 10.72964

1000467.9726461915
第7419组系数
[-0.37288969 -0.34745494  0.1139112   5.69726859]
0.35125791984487637
第7420组系数
[ 0.53956436 -0.25908331  0.30333092  7.09056458]
0.33194617696266016
第7421组系数
[1.62922418 0.28605426 0.06048653 7.3367045 ]
0.39389610049110907
第7422组系数
[-0.6697064  -0.11111111 -0.68129314  4.81718271]
1.2091875131530179
第7423组系数
[-0.74065615 -1.875323   -1.04215116  4.06047688]
8.618997120662035
第7424组系数
[-1.32092292 -0.50295902 -0.46977302  5.01404675]
4.072109419527219
第7425组系数
[ 2.94773925 -1.33983171 -0.09438362  7.13613524]
1.1051518676453627
第7426组系数
[-0.02389346 -0.14727771 -0.16161659  6.10199625]
0.36149576231324976
第7427组系数
[-0.23242835 -0.25956113  0.1354232   6.10898175]
0.32122272145292324
第7428组系数
[ 0.49576923  0.47653846 -0.43661466  6.37796491]
0.48433860058673356
第7429组系数
[0.84724834 0.38679245 0.05717103 7.37768997]
0.40354421084810815
第7430组系数
[-0.11182873 -0.15034087  0.50146514  6.99871845]
0.4840356240541358
第7431组系数
[5.37966305e-01 1.21367096e-01 3.334009

7.520605371003248e+20
第7523组系数
[ 0.68683401 -0.34254192 -0.15483619  6.47719697]
0.313654831006423
第7524组系数
[ 0.2006706   0.07961513 -0.09972212  6.5859672 ]
0.36802773181344345
第7525组系数
[ 1.86171171 -0.42252252  0.09979279  7.15810532]
0.4467151747294725
第7526组系数
[-0.0640341   0.74329261 -0.12935291  6.32498699]
0.39011259441121565
第7527组系数
[ 0.07489289  0.07771411 -0.05910307  6.34838925]
0.2678035461484385
第7527组系数
[ 0.86703185  0.13266697 -0.05526494  6.97002507]
0.3114350752007312
第7528组系数
[-17.01878567   4.29134098   7.75132902  15.40466946]
2.716838660537127e+33
第7529组系数
[ 0.09524661 -0.06115713 -0.31024114  6.09994825]
0.42699000212132315
第7530组系数
[ 0.30058954 -0.00792501 -0.13936704  6.31403382]
0.25261248479898324
第7531组系数
[-0.32302     0.07402447  0.7347772   6.86888079]
0.4099798053157892
第7532组系数
[ 0.62011675 -2.45621913 -0.44607095  5.59413651]
26.57213354878455
第7533组系数
[-0.45833333  1.07896103 -0.10286536  5.97241454]
0.4954794998190809
第7534组系数
[-20.          -4.400361

0.3649682193569481
第7626组系数
[ 1.45192089  3.42782451  2.70516026 11.95439873]
1.5148662765563068
第7627组系数
[ 1.39285714e+00 -5.20943771e-03  1.80793030e-01  7.35278495e+00]
0.35820375325337295
第7628组系数
[-0.0220943   0.26740851 -0.11136358  6.32695051]
0.3411000086714026
第7629组系数
[ 0.43006341 -3.22491608  0.21857516  5.55046997]
471.0869352623597
第7630组系数
[-0.35331044 -0.05034232  0.10903439  5.81516771]
0.3352378469256737
第7631组系数
[ 1.69177681 -2.35649952 -0.09960314  6.58819085]
22.501709198912405
第7632组系数
[ -4.66666667   3.         -10.44927536 -10.61710145]
1.3741042547695498e+21
第7633组系数
[ 0.71276457 -0.0094562   0.1603781   7.06492806]
0.2815545258987705
第7634组系数
[ 1.43811468 -0.03281963 -0.07771338  7.09883606]
0.3689660136998687
第7635组系数
[ 0.67512564  0.23620962 -0.04976441  6.91374489]
0.3003108850420994
第7636组系数
[17.29383386 16.45168099 38.22870496 74.00999095]
1.0812915335004006e+19
第7637组系数
[-0.06001606 -0.11039743  0.65064231  6.74087214]
0.34749052218279486
第7638组系数
[ 0.723

51.06020632893585
第7730组系数
[ 0.74912328 -1.30294038 -1.11109717  4.40905565]
1.393012684945271
第7731组系数
[ 1.13150392  3.52610206  7.26837963 21.10510888]
923.0009663532142
第7732组系数
[ 0.02530254 -0.47058824  0.07707595  5.9173587 ]
0.3011803661498455
第7733组系数
[ 4.89311325 -3.95636134 -3.11716953  3.22300095]
7031.576220958477
第7734组系数
[ 4.80888819 -7.89606515 -2.88146088  1.11452059]
139479962114.78848
第7735组系数
[1.80780832 0.31692603 0.48125043 8.12512922]
0.462386351403777
第7736组系数
[-0.17344654  1.01700874  0.07260169  6.06189891]
0.47522857264666296
第7737组系数
[-0.61034611 -1.62965389 -1.34381762  3.39073227]
8.041693253467413
第7738组系数
[ 3.89103927  7.49604932 -0.35470277 10.87553173]
2.64966496242921
第7739组系数
[ 0.04478185  0.16003372 -0.19402668  5.85775295]
0.32835622257274677
第7740组系数
[-0.25622789 -0.33783522 -0.09857604  5.84281389]
0.41301806534284147
第7741组系数
[-46.875041    22.47195802  54.35060676  47.32739915]
1.5312663048756277e+90
第7742组系数
[0.62508445 0.46903393 0.29196482 7.5

0.36061320499641913
第7834组系数
[0.1622403  1.50993142 0.21168439 7.2763691 ]
0.44787926037647624
第7835组系数
[ 0.83982202 -0.67754449  0.71879588  7.28267583]
0.4923531160307612
第7836组系数
[-10.4258085  -13.52346227   2.7878884    4.79466709]
2.566248448647116e+25
第7837组系数
[-5.14185672 -0.4923136   5.7973278   4.88757245]
37220.80213644602
第7838组系数
[-0.249016   -0.0406556  -0.03275243  5.74980871]
0.3136419844095794
第7839组系数
[-0.68761246 -1.38096598  3.20410728  9.47580932]
7.030818161174977
第7840组系数
[1.35260282 0.0808168  1.40030678 8.86013632]
0.5977397103864742
第7841组系数
[-0.08017241 -0.76637931 -0.20279877  5.3950444 ]
0.4105317421519312
第7842组系数
[ -97.58423913 -228.88315217  274.04619565  103.71478261]
第7842组系数
[ 0.14717327 -0.26332173  0.3018843   6.86257568]
0.37808915769993423
第7843组系数
[-0.21865079 -0.44943097 -0.01911171  5.65013632]
0.32532525325703976
第7844组系数
[ 0.4635122  -1.74144715  0.68286557  6.92132785]
3.3436040235251463
第7845组系数
[-0.60989011 -3.07142857  5.71428571 11.401593

1.1244057907982032
第7939组系数
[0.88384731 0.99736621 0.00906989 7.74133322]
0.644451523908744
第7940组系数
[ 0.56570353 -0.05939166  0.00868163  6.90521435]
0.3229254377608969
第7941组系数
[ 0.18632206 -0.80956694 -0.04223743  5.94651812]
0.4015490619479883
第7942组系数
[0.59707857 0.9099305  0.13316386 7.49004278]
0.4371431744520331
第7943组系数
[ 0.50669547 -0.26241529  0.25180194  7.06816964]
0.3568819545833243
第7944组系数
[1.19479284 0.41469077 0.3855419  8.03486796]
0.50554851843378
第7945组系数
[ 0.01165657 -0.12713058 -0.18094098  5.92597443]
0.28095966505488806
第7946组系数
[ 1.45559846 -3.2020592  -2.36164736  2.35480051]
198.55399082297973
第7947组系数
[ 0.72349654 -0.28465438 -0.13952291  6.45838734]
0.2926182667581556
第7948组系数
[ 0.10786058 -0.04388216  0.37585349  6.77345749]
0.2644207798345315
第7949组系数
[ 0.94071396 -0.18857941 -0.21998414  6.63369318]
0.34397839114012857
第7950组系数
[-0.03044676 -0.36525948  0.36295144  6.16932284]
0.35653668222893203
第7951组系数
[2.26315136 0.26457312 0.30339154 8.03219496]
0.